"""All static data: jokes, facts, motivational quotes, love quotes, riddles."""

JOKES = [
    "Müəllim şagirdə: 'Suyun kimyəvi formulu nədir?' Şagird: 'H-I-J-K-L-M-N-O!' Müəllim: 'Bu nədir?!' Şagird: 'H to O!' 😄",
    "Arvad ərinə: 'Mağazaya get, bir litr süd al, yumurta varsa 6 dənə al.' Ər 6 litr süd gətirir. Arvad: 'Niyə 6 litr?!' Ər: 'Yumurta var idi da!' 😂",
    "Həkim xəstəyə: 'Siqaret çəkirsiniz?' Xəstə: 'Bəli.' Həkim: 'Çəkməyin.' Xəstə: 'Pulsuz məsləhətmi?' Həkim: 'Bəli.' Xəstə: 'Mən də.' 😄",
    "Müəllim: 'Cümləni tamamla: İt hürür, karvan...' Şagird: 'İt hürür, karvan yenə geri gəlir.' 😄",
    "Restoranda ofisiantdan: 'Bu ördəkdirmi?' Ofisiant: 'Bəli.' Müştəri: 'Bəs niyə toyuq kimi görünür?' Ofisiant: 'Çünki paltarını dəyişib.' 😂",
    "Uşaq anasına: 'Ana, ata niyə hər gün işə gedir?' Ana: 'Pul qazanmaq üçün.' Uşaq: 'Bəs niyə pulu qurtaranda işdən çıxmır?' 😄",
    "Bir nəfər həkimə: 'Doktor, qulağım çox ağrıyır.' Həkim: 'Nə vaxtdan?' Nəfər: 'İki həftədən bəri.' Həkim: 'Niyə bu qədər gözlədiniz?' Nəfər: 'Umurdum keçər.' Həkim: 'Bəs keçmədi?' Nəfər: 'Keçdi, indi digəri ağrıyır.' 😂",
    "Taksi sürücüsü: 'Hara?' Sərnişin: 'Əvvəl mənzilimə, sonra işimə.' Sürücü: 'Yəqin ki, iş çoxdur.' Sərnişin: 'Yox, açarı evdə unutmuşam.' 😄",
    "İki balıq suda üzürdü. Biri digərinə: 'Suyun temperaturu necədir?' Digəri: 'Bilmirəm, mən balıqçıyam.' 😄",
    "Şagird müəllimə: 'Niyə yarımçıq cümləni tamamlamırsınız—' Müəllim: 'Niyə mən?' 😂",
    "Həkim: 'Diqqətlə dinləyin, vəziyyətiniz ciddidir. Hər gün 8 saat yuxu lazımdır.' Xəstə: 'Doktor, mən hər gecə 10 saat yatıram.' Həkim: 'Gecə yox, gündüz!' 😄",
    "Oğul atasına: 'Ata, uçmağı öyrənmək istəyirəm.' Ata: 'Yaxşı.' Oğul: 'Gərək pul verəsən.' Ata: 'Əvvəl uç, sonra danışarıq.' 😂",
    "Bir adam kompüterə baxıb: 'Silinmə!' Kompüter: 'Silinmə əminsiniz? Bəli / Xeyr.' Adam: 'Bəli!' Kompüter: 'Silindiniz.' Adam: '...' 😄",
    "Müəllim: 'Kim Napoleonu öldürdü?' Sinif sükutda. Axırda bir şagird: 'Mən deyildim, and olsun!' 😂",
    "İşçi müdirə: 'Maaşımı artırmaq istəyirəm. Üç müəssisə məni istiyor.' Müdir: 'Hansılar?' İşçi: 'İşsizlik idarəsi, bank və ev sahibi.' 😄",
    "Bir nəfər aptekə girib: 'Yuxu dərmanı verin.' Aptekar: 'Həkim resepti lazımdır.' Adam: 'Amma arvadım üçündür.' Aptekar: 'Niyə?' Adam: 'Hər gecə danışır, yata bilmirəm.' 😂",
    "Uşaq: 'Ata, bu axşam ulduzlar niyə görünmür?' Ata: 'Çünki buludlardır.' Uşaq: 'Bəs ulduzlar haradır?' Ata: 'Buludların arxasında.' Uşaq: 'Bəs buludlar haradır?' Ata: 'Yat artıq.' 😄",
    "Dostlar görüşdə: 'Niyə gec qaldın?' Adam: 'Çarxpənar gördüm.' Dost: 'Nə? Niyə?' Adam: 'Yazırdı: Sola dön. Döndüm. Sağa dön. Döndüm. Düz get. Getdim. Geri dön. Döndüm...' 😂",
    "Arvad ərinə: 'Niyə bu qədər yatırsan?' Ər: 'Yuxuda işləyirəm.' Arvad: 'Nə iş görürsən?' Ər: 'Pul sayıram.' 😄",
    "Şagird: 'Müəllim, bu sual çox çətin idi.' Müəllim: 'Bilirəm.' Şagird: 'Niyə verdiniz onda?' Müəllim: 'Çünki bu imtahandan keçənlər gerçəkdən öyrənib.' Şagird: '..Bəs keçməyənlər?' Müəllim: 'Onlar da bir şey öyrəndi: hazırlaşmağı.' 😂",
    "Həkim: 'Nə vaxtdan bu hal var?' Xəstə: 'Bilmirəm.' Həkim: 'Sabah gəlin.' Xəstə: 'Sabah niyə?' Həkim: 'Çünki bu gün yalnız bilmirəm deyirəm.' 😄",
    "Uşaq: 'Ana, mən böyüyəndə pilot olacağam.' Ana: 'Gözəldir.' Uşaq: 'Sən də gəlisən, pulsuz uçurduram.' Ana: 'Sağ ol.' Uşaq: 'Amma əvvəlcə bilet al.' 😂",
    "Dost dostuna: 'Mən iyirmi il evli oldum.' Digəri: 'Gözəldir!' Birinci: 'Sonra ayılıb başa düşdüm ki, artıq çox gec.' 😄",
    "Müəllim: 'Bitkinin inkişafı üçün nə lazımdır?' Şagird: 'Torpaq, su, günəş.' Müəllim: 'Əla! Bəs ağac üçün?' Şagird: 'Odunçu lazım deyil.' 😂",
    "Adam dükandarla: 'Bu pendir nə vaxtdan var?' Dükandar: 'Bu gün gəlib.' Adam: 'Bəs bu qoxu?' Dükandar: 'Pendir belə olur.' Adam: '...Siz bunu yeyirsiniz?' Dükandar: 'Mən vegananım.' 😄",
    "Şagird: 'Müəllim, imtahanda bu sualı verəcəksiniz?' Müəllim: 'Bəli.' Şagird: 'Cavabı da verəcəksiniz?' 😂",
    "Həkim xəstəyə: 'Hər gecə yatmadan əvvəl isti su için.' Xəstə həftə sonra: 'Doktor, isti su içirəm amma yenə yata bilmirəm.' Həkim: 'Niyə?' Xəstə: 'Çünki çaydan savayı içmirəm.' 😄",
    "Arvad: 'Buzdolabına bax, nə görsən al.' Ər mağazadan qayıdır: '6 ədəd gətirdim.' Arvad: 'Nə?' Ər: 'Heç nə — buzdolabı boş idi.' 😂",
    "İki nəfər meşədə: 'Ayı qaçdı!' Biri: 'Ayıdan qaçmaq olmur, sürəti 60 km/s.' Digəri: 'Mən ayıdan deyil, səndən tez qaçmalıyam.' 😄",
    "Şagird: 'Müəllim, insan öldükdən sonra ruhu göyə gedir mi?' Müəllim: 'Niyə soruşursun?' Şagird: 'Çünki qiymətimi öldürdünüz.' 😂",
    "Adam həkimə: 'Hər gün başım ağrıyır.' Həkim: 'Yuyursunuz?' Adam: 'Bəli.' Həkim: 'Nə ilə?' Adam: 'Şampun.' Həkim: 'Cəhd edin sabunla.' Adam: 'Amma saçsızam.' Həkim: '...' 😄",
    "Arvad ərinə: 'Qardaşım bizə gəlir, üç ay qalacaq.' Ər: 'Yaxşı.' Arvad: 'Sevindin?' Ər: 'Bəli, çünki bilirəm ki, üç ay keçib gedəcək.' 😂",
    "Pilot: 'Sərnişinlər, sol mühərrik sıradan çıxdı.' Sükut. 'Amma narahat olmayın, üç mühərrikimiz var.' Biraz sonra: 'Sağ mühərrik də dayandı.' Daha böyük sükut. 'Amma iki mühərrikimiz var.' Axırda: 'İndi qalın diqqətlə mənə baxın...' 😄",
    "Dost dostuna: 'Qadın necədir ki, bütün sirrini onunla bölüşürsən?' Digəri: 'Qardaşım arvadım haqqında danışma.' 😂",
    "Balıq bildirdi: 'Niyə hər yerdə su var, amma içəcək yoxdur?' 😄",
    "Müəllim: 'Kim məktəbə gec gəlsə, dərsdən qovaram.' Şagird gec gəldi. Müəllim: 'Niyə gecikdiniz?' Şagird: 'Məktəbin saatı 5 dəqiqə tez idi.' 😂",
    "Adam dost ilə mübahisə edir: 'Sən anlamırsın!' Dost: 'Anlamıram.' Adam: 'Görürsən, yenə anlamırsan.' 😄",
    "Uşaq: 'Niyə it xırda olduqda boylanır, böyüdükdə boylanmır?' Ana: 'Niyə?' Uşaq: 'Çünki uşaqlıqda görmür.' 😂",
    "Müəllim: 'Ən uzun çay hansıdır?' Şagird: 'Bizdə axan.' Müəllim: 'Yox, Nil.' Şagird: 'O daha uzun axır.' 😄",
    "Həkim: 'Siqaret, spirt, yağlı yemək yaramaz.' Xəstə: 'Bəs nə?' Həkim: 'Meyva, tərəvəz, idman.' Xəstə: 'Ömrüm uzanacaq?' Həkim: 'Yox, amma daha uzun hiss edəcək.' 😂",
    "Arvad: 'Burada 50 manat qoymuşdum, indi 40 var.' Ər: 'Gözün yanıldı.' Arvad: 'Yox, sənin əllərin.' 😄",
    "İki sərxoş danışırdı. Biri: 'Bu yol haradandır?' Digəri: 'Bilmirəm.' Birinci: 'Yaxşıdır ki, biz onu tikmirik.' 😂",
    "Oğlan qıza: 'Sənə hər şeyimi verərdim.' Qız: 'Hər şeyin nədir?' Oğlan: 'İki manat yarım.' 😄",
    "Atası oğluna: 'Niyə imtahanı keçmədin?' Oğlan: 'Müəllim sualı düz vermədi.' Atası: 'Necə?' Oğlan: 'O soruşdu ki, bildiklərini yaz. Mən bildiklərimi yazdım, o da dedi az.' 😂",
    "Həkim: 'Siz çox az yatırsınız.' Xəstə: 'Niyə?' Həkim: 'Çünki hər gün iş həyatı sizi yorur.' Xəstə: 'Bəs nə etməliyəm?' Həkim: 'İşdən çıxın.' Xəstə: 'Onda ailəmi necə bəsləyəcəyəm?' Həkim: 'Bu artıq mənim problemim deyil.' 😄",
    "Uşaq: 'Ata, Ay niyə gecə çıxır?' Ata: 'Çünki gündüz onu görmək lazım deyil.' Uşaq: 'Niyə?' Ata: 'Çünki günəş var.' Uşaq: 'Bəs gecə?' Ata: 'Yat.' 😂",
    "Şagird: 'Ev tapşırığımı itirdim.' Müəllim: 'Niyə?' Şagird: 'Küləkdə uçdu.' Müəllim: 'Bəs niyə tutmadın?' Şagird: 'Yellənçəkdə idim.' 😄",
    "Bir adam qaçırdı. Dost: 'Niyə qaçırsan?' Adam: 'Həkim dedi gün ərzində 3 km qaçın.' Dost: 'Üç gündür görürəm səni.' Adam: 'Bəli, 9 km oldum.' 😂",
    "Oğlan anasına: 'Qız məni sevmir.' Ana: 'Niyə?' Oğlan: 'Yazdım: Cavab ver, yoxsa bunu oxumayacaqsan. O da cavab vermədi.' 😄",
    "Müəllim: 'Siz bunu haradan köçürdünüz?' Şagird: 'Heç yerdən.' Müəllim: 'Bəs niyə qonşunuzla eynidir?' Şagird: 'Biz eyni kitabdan oxuduq.' 😂",
    "İki dost danışır. Biri: 'Ən pis gün nə idi?' Digəri: 'Anadan olduğum gün.' Biri: 'Niyə?' Digəri: 'Başlanğıcdan bəri problem var.' 😄",
    "Arvad: 'Niyə heç vaxt mənə gül almırsan?' Ər çiçəkçiyə gedir. Qayıdır: 'Süd aldım.' Arvad: 'Niyə?' Ər: 'Çiçəkçi yanındakı dükan idi.' 😂",
    "Oğlan qıza: 'Sən məni tərk etsən, dünyadan gedəcəyəm.' Qız: 'Hara?' Oğlan: 'Avropaya.' 😄",
    "Müəllim: 'İqlimi kim idarə edir?' Şagird: 'Hava.' Müəllim: 'Yox, iqlim sistemidir.' Şagird: 'Bəs hava niyə hər gün dəyişir?' 😂",
    "Bir insan: 'Siqaret içmirəm, spirt içmirəm, ət yemirəm.' Dost: 'Niyə?' Adam: 'Pulum yoxdur.' 😄",
    "Həkim: 'Sizi bir ay xəstəxanada saxlamalıyıq.' Xəstə: 'Bir ay?! Görünür xəstəxananın krediti var.' 😂",
    "Uşaq: 'Ana, bu böcək niyə ölmür, vururum amma ölmür.' Ana: 'Plastik böcəkdir.' 😄",
    "Dost: 'Bir problem var.' Digəri: 'De.' Birinci: 'Unudum.' Digəri: 'Yaxşı problem.' 😂",
    "İşçi müdirə: 'Niyə maaşım azdır?' Müdir: 'Çünki az işləyirsiniz.' İşçi: 'Az işə az maaş.' Müdir: 'Bəli.' İşçi: 'Bəs niyə çox işlədikdə eyni maaş olur?' 😄",
    "Arvad: 'Bu paltarı sevirsən?' Ər: 'Bəli.' Arvad: 'Almağa dəyərmi?' Ər: 'Sənin saydığın bilər.' Arvad: '500 manat.' Ər: 'Xeyr.' 😂",
    "Qız oğlana: 'İlk görüşdə bağlamaq istəyirsən?' Oğlan: 'Niyə?' Qız: 'Çünki baxışın bağlayır.' Oğlan: 'Hə... Yox, gözlüyümdən baxırdım.' 😄",
    "Müəllim: 'Valideynlərinizə söyleyin ki, açıq gün var.' Şagird: 'Anama söyləsəm gəlir, amma anam sizi tanıyır.' Müəllim: '...Ev tapşırığı çoxaldım.' 😂",
    "Həkim: 'Bu dərmanı hər gün için.' Xəstə: 'Nə vaxt?' Həkim: 'Yemək öncəsi.' Xəstə: 'Nə yemək?' Həkim: 'İstənilən.' Xəstə: 'Bəs əgər yeməsəm?' Həkim: 'Onda siz heç vaxt dərman içmirsiniz.' 😄",
    "Dost: 'Niyə hər gün futbol izləyirsən?' Adam: 'Çünki arvadım izlər, gərək mən də izləyim.' Dost: 'Qadınlar futbolu sevirlər?' Adam: 'Yox, amma o dedikdə mən gedirəm, futbol olanda qalıram.' 😂",
    "İki adam yarışdı. Biri qaçdı, birincisi oldu. Digəri dedi: 'Sən qaydaları pozurdun.' Birincisi: 'Hansı qaydalar?' Digəri: 'Qaçmamaq lazım idi.' 😄",
    "Müəllim: 'Bu mövzunu keçdik.' Şagird: 'Nə vaxt?' Müəllim: 'Keçən dərs.' Şagird: 'Mən yox idim.' Müəllim: 'Bəs indi varsan.' Şagird: 'Amma keçən dərsi keçmirəm.' 😂",
    "Qız: 'Mən görüntülü zəng etmək istəmirəm.' Oğlan: 'Niyə?' Qız: 'Çünki hazır deyiləm.' Oğlan: 'Gözəlsən elə.' Qız: 'Bilirəm, amma saçım düzəlməyib.' 😄",
    "Arvad: 'Bu ay xərcləri azaltmalıyıq.' Ər: 'Yaxşı.' Arvad: 'Başlayaq.' Ər: 'Handan?' Arvad: 'Sən restorandan, mən alış-verişdən.' Ər: '...' 😂",
    "Adam pişiyə: 'Sən niyə həmişə yatırsan?' Pişik onu saymadı. Adam: 'Sual vermərəm artıq.' 😄",
    "Müəllim: 'Bu sualın cavabını bilən?' Hamı sükutda. Müəllim: 'Heç kim?' Şagird: 'Mən bilirəm amma demirəm.' Müəllim: 'Niyə?' Şagird: 'Sürpriz.' 😂",
    "Bir adam telefona baxırdı 3 saatdır. Arvadı: 'Nə edirsin?' Adam: 'Baxıram.' Arvad: 'Nəyə?' Adam: 'Vaxt keçir.' 😄",
    "Uşaq: 'Müəllim, ev tapşırığı verəcəksiniz?' Müəllim: 'Bəli.' Uşaq: 'Niyə?' Müəllim: 'Niyə soruşursan?' Uşaq: 'Çünki ev tapşırığı verməyəcəksinizsə, məktəbə gələcəkdim.' 😂",
    "Dost: 'Niyə hər il doğum günümdə yaddan çıxarırsın?' Adam: 'Çünki hər il eyni gündür.' 😄",
    "İşçi: 'Gecikdim çünki zəlzələ oldu.' Müdir: 'Bizim şəhərdə zəlzələ olmadı.' İşçi: 'Bizdə oldu.' Müdir: 'Harada yaşayırsınız?' İşçi: 'Beşinci mərtəbədə.' 😂",
    "Ana uşağa: 'Paltoyu geyin.' Uşaq: 'Soyuq deyil.' Ana: 'Mən soyuq deyirəm.' Uşaq: '..Siz geyin onda.' 😄",
    "Qız: 'Sabah görüşək?' Oğlan: 'Saat neçədə?' Qız: '12.' Oğlan: 'Günorta, yoxsa gecə?' Qız: 'Günorta.' Oğlan: 'Yaxşıdır, gecə çox gec olardı.' 😂",
    "Müəllim: 'Ürəyinizin nə istədiyin yazın.' Şagird 10 dəqiqə düşündü, sonra yazdı: 'Nahar fasiləsi.' 😄",
    "Ər arvada: 'Mən sənin ən yaxşı dostunuq.' Arvad: 'Sən mənlə evlisiniz.' Ər: 'Bəli, ən yaxın.' 😂",
    "Adam qaçırdı. Dost: 'Hansı marafona hazırlaşırsın?' Adam: 'Avtobusa.' 😄",
    "Bir nəfər aptekə girdi: 'Yaxşı dərman var?' Aptekar: 'Nəyə?' Adam: 'Həyata.' Aptekar: '...' 😂",
    "Uşaq: 'Böyüyəndə nə olacağam?' Ata: 'Hər şey ola bilərsən.' Uşaq: 'Batman ola bilərəmmi?' Ata: 'O qədər pul gərəkdir ki...' 😄",
    "Müəllim: 'Bu gün dərs yoxdur.' Şagirdlər: 'Ura!' Müəllim: 'Çünki imtahandır.' Şagirdlər: '...' 😂",
    "Arvad: 'Bu gün mənə gül al.' Ər gətirir. Arvad: 'Niyə bu rəngdə?' Ər: 'Sevdiyim rəng.' Arvad: 'Mən sevmirəm.' Ər: 'Mən aldım.' 😄",
    "Dost: 'Niyə bu qədər sükutda otururdun?' Adam: 'Düşünürdüm.' Dost: 'Nə?' Adam: 'Nə düşündüyümü unudum.' 😂",
    "Balıq suya sualını verdi: 'Suda yaşamaq necədir?' Su: 'Bilmirəm, başqa cür olmayıb ki.' 😄",
    "Qız oğlana: 'Sən məni dünyadan çox sevirsən?' Oğlan: 'Bəli.' Qız: 'Futboldan çox?' Oğlan: 'O başqa sualdır.' 😂",
    "Müəllim: 'Kim Avropanın ən böyük dağını bilir?' Şagird: 'Mont Blank.' Müəllim: 'Əla! Siz öz başınıza öyrəndiniz?' Şagird: 'Bəli.' Müəllim: 'Əla əməl. Bəs Asiyada?' Şagird: 'Evertəst.' Müəllim: 'Everest. Amma yenə əla.' Şagird: 'Sağ olun. Mən Youtube izlədim.' 😄",
    "Adam kompüter ustasına: 'Kompüterim yavaşdır.' Usta: 'Kaş siz gəlməsəydiniz.' Adam: 'Niyə?' Usta: 'Çünki ev tapşırığınızdan sürətli iş görmürdünüz.' 😂",
    "İki qoca danışırdı. Biri: 'Mən 90 yaşıma qədər yaşayacağam.' Digəri: 'Niyə?' Birincisi: 'Çünki doktor dedi ki, 80 yaşa qədər yoxsunuz.' 😄",
    "Uşaq: 'Ana, məktəbdə pis notum çıxdı.' Ana: 'Niyə?' Uşaq: 'Müəllim.' Ana: 'Niyə?' Uşaq: 'O dedi ki, hər şey öz əlindədir. Mən də öz əlimlə yazdım, o da pis not verdi.' 😂",
    "Arvad ərinə: 'Sən məni niyə sevirsən?' Ər: 'Bilmirəm.' Arvad: '??' Ər: 'Bəzi şeylər izah edilmir, hiss edilir.' Arvad: 'Romantikdir!' Ər: 'Əslən cavab düşünə bilmədim.' 😄",
    "Adam sürücüyə: 'Məni dəqiq bu ünvana aparın.' Sürücü: 'Uzaqdır.' Adam: 'Bilirəm.' Sürücü: 'Bəs niyə gedirsiniz?' Adam: 'Çünki orada evim var.' 😂",
    "Müəllim: 'Niyə hər gün gec gəlirsən?' Şagird: 'Evim uzaqdır.' Müəllim: 'Yaxına köç.' Şagird: 'Hər dəfə köçsəm, yenə uzaq olacaq.' 😄",
    "Bir adam hər gün parka gedirdi. Bir gün gəlmədi. Növbəti gün gəlib dedi: 'Dünən gəlmədim.' Park: '...' 😂",
    "Qadın: 'Sizi ilk dəfə görürəm, amma tanış kimi hiss edirəm.' Adam: 'Bəli, mən tanışınızın tanışının qardaşının dostuyam.' Qadın: '...Yəqin ki, siz Azərbaycanlısınız.' 😄",
]

FACTS = [
    "Bal heç vaxt xarab olmur. Misir piramidalarında 3000 illik bal tapılıb! 🍯",
    "Okeanlar Yer kürəsinin 71%-ni əhatə edir, amma yalnız 5%-i öyrənilib. 🌊",
    "İnsan beyni 2,5 petabayt məlumat saxlaya bilər — bu 3 milyon saatlik TV-yə bərabərdir! 🧠",
    "Meymunlar bananı sapından deyil, alt tərəfdən soyurlar. 🐒",
    "Dünyada qarışqaların ümumi çəkisi bütün insanların çəkisindən çoxdur. 🐜",
    "Filippin ölkəsi 7641 adadan ibarətdir. 🏝️",
    "Şimşək eyni yerə ortalama ildə 40 dəfə vurur. ⚡",
    "Balıqların yaddaşı 3 saniyə deyil — onlar aylarla yadda saxlaya bilir. 🐟",
    "Dünyanın ən hündür dağı Everest hər il 4 mm böyüyür. ⛰️",
    "Qar dənəciklərinin heç biri bir-birinə bənzəmir. ❄️",
    "Fil, öz əksini tanıya bilən yeganə məməlilərdən biridir. 🐘",
    "Göyqurşağı əslində dairəvidir, amma yer üzündən yalnız yarısı görünür. 🌈",
    "İnsan gözü 10 milyon fərqli rəngi fərqləndirə bilir. 👁️",
    "Venus günəş ətrafında bir dövr etməkdən daha sürətli öz oxu ətrafında dövr edir. 🪐",
    "Dünyada hər saniyə 100 şimşək düşür. ⚡",
    "Pişiklər 19 fərqli səs çıxara bilirlər. 🐱",
    "Zəhmli görünən köpək balığı balalarına qulluq edir. 🦈",
    "İnsan əli gündə ortalama 1500 dəfə üzünə toxunur. 🤚",
    "Oxford Universiteti Azteklərin süqutundan 200 il öncə qurulub. 🏛️",
    "Muz texniki olaraq giləmeyvədir, çiyələk isə deyil. 🍌",
    "Bir insan ömrü boyu ortalama 6 ay qırmızı işıqda gözləyir. 🚦",
    "Pələng qulaqlarını müstəqil döndərə bilir. 🐯",
    "Dünyanın ən köhnə canlı ağacı 5000 yaşlıdır. 🌲",
    "Arılar möhtəşəm ingilis dilini başa düşür — rəqsləri ilə yönü izah edirlər. 🐝",
    "Qurğuşun əsrlər boyu boya kimi işlədildi, əslində zəhərlidir. ☠️",
    "İnsanın qan damarlarını uzatsan Yer kürəsini iki dəfə dolanardı. 🩸",
    "Nərə balığı 100 yaşa qədər yaşaya bilir. 🐟",
    "Mars üzərindəki gün 24 saat 37 dəqiqədir. 🔴",
    "Koala barmaq izləri insanın barmaq izinə o qədər bənzəyir ki, ayırd etmək çətindir. 🐨",
    "Dünyada hər saniyə 4 uşaq doğulur. 👶",
    "Sevgi hormonu oksitosinin müalicəvi gücü var. ❤️",
    "Beyin özünə ağrını hiss etdirmir — cərrahlar beyni bihuşsuz əməliyyat edə bilir. 🧠",
    "Yarasalar yalnız gecə aktiv deyil — bəzilər gündüz də ovlanır. 🦇",
    "Dünyada 1 milyarddan çox it var. 🐕",
    "Zəfəran dünyada ən bahalı ədviyyatdır — 1 kq üçün 3000 dollar. 🌺",
    "İnsan ömrü boyunca ortalama 35 ton qida yeyir. 🍽️",
    "Göyərçinlər 1000 km-dən artıq məsafəni xatırlayıb evə qayıda bilirlər. 🕊️",
    "Stres qəbul edən insan daha az xəstəliyə meyillidir. 💪",
    "Ölkə adları içindən ən uzunu 'United Kingdom of Great Britain and Northern Ireland'dir. 🇬🇧",
    "Delfin hər yarım beynini növbə ilə yatırır, digər yarısı oyaq qalır. 🐬",
    "İnsanlar gülümsəyəndə 43 əzələ işləyir, qaşqabaq tutanda isə yalnız 17. 😊",
    "Kəpənəklər tat alma qabiliyyətini ayaqlarında daşıyır. 🦋",
    "Hər il 1 milyon ton saç kəsilir. ✂️",
    "Amazonlar meşəsi dünyada istehsal olunan oksigenin 20%-ni verir. 🌿",
    "Çin səddinin uzunluğu 21000 km-dən artıqdır. 🏯",
    "Günəş işığı Yerə çatmaq üçün 8 dəqiqə 20 saniyə sərf edir. ☀️",
    "Əqrəb 1 həftəyə qədər nəfəssiz qala bilir. 🦂",
    "İnsanlar ağlayanda sol gözdən əvvəl sağ gözdən yaş gəlir. 😢",
    "Dünyada 2800-dən çox dil var. 🌍",
    "Pivə qədim Misirdə işçilərə maaş kimi verilirdi. 🍺",
    "Avstraliyanın Böyük Mərcan Rifi kosmosdan görünür. 🌊",
    "Fıl 50 km məsafəni hidrosezinlə hiss edə bilir. 🐘",
    "İnsan bədənindəki hüceyrələrin 60% -i bakteriyadır. 🦠",
    "Balıqların dili var amma dad bilmirdilər — əslən kimi billər? 🐟",
    "Kvarsa (Qvars) saatı hər gün günəşin enerjisi ilə işlədir. ⌚",
    "İnsan tükünün uzunluğu 1 metrə qədər uzana bilər. 💇",
    "Bayquş boyununu 270 dərəcəyə qədər çevirə bilir. 🦉",
    "Kaktus 200 litr suya qədər saxlaya bilir. 🌵",
    "Dağ dövrü: Himalay hər il 5 sm böyüyür. ⛰️",
    "Mavi balina ürəyi insan qədər böyükdür. 🐋",
    "Müasir smartfonlar 1969-cu ildə Aya uçan Apollo raketindən qat-qat güclüdür. 📱",
    "Meş qarası sərçəsi öz rəfiqinə hər il hədiyyə gətirir. 🐦",
    "İnsan ağciyərini düzlətsen bir tennis meydanını örtərdik. 🫁",
    "Yatarkən adam ağlaya bilmir — lakin yuxuda hiss edir. 😴",
    "Dünyanın ən kiçik ölkəsi Vatikan — cəmi 0,44 km². 🏙️",
    "Kənd toyuğu orta hesabla 250 yumurta qoyur. 🥚",
    "İnsan dişi əzməsi çeliyin sərtliyindən 5 dəfə möhkəmdir. 🦷",
    "Şahin gözlə 3 km məsafədən siçan görə bilir. 🦅",
    "Okean ən dərin nöqtəsi 11 km-dir — Mariana çuxuru. 🌊",
    "İnsan nəfəs alarkən sağ burun deliyi daha güclü işləyir. 👃",
    "Dünyada 100 milyon il əvvəl 3 metr uzunluğunda kəpənəklər yaşayıb. 🦋",
    "Əksər insanlar gün ərzindəki vaxtın 1/3-ni telefona baxır. 📱",
    "Şimpanzə tərəfindən öyrənilmiş 300-dən çox işarə dili var. 🐵",
    "Kəhrəba içindəki həşəratlar 100 milyon il yaşlı ola bilir. 🪲",
    "Mis çox güclü antibakterialdır — buna görə qədim Misirdə istifadə edilirdi. 🪙",
    "İnsan orta ömrü boyunca 5 ildən çox nahar fasiləsini yatmaqda keçirir. 😴",
    "Günəş sistemimiz galaktikamızın mərkəzini 225 milyon ildə bir dəfə dolanır. 🌌",
    "Həşəratların nəfəs borucuqları bütün bədən boyunca yayılıb. 🐝",
    "Krokodil dili ilə yerini dəyişdirə bilmir. 🐊",
    "Bal arısı ömrü boyunca cəmi 1/12 çay qaşığı bal istehsal edir. 🍯",
    "İnsan bədəni ildə 300 milyon hüceyrə məhv edir. 🫀",
    "Qızılı balığın yaddaşı 3 aylıqdır — 3 saniyə əfsanədir. 🐠",
    "Dünyanın ən iri çiçəyi Rafflesia — diametri 1 metrə çatır. 🌸",
    "Gözlər ömrü boyunca bir dəfə naz çəkir — həmişə eyni ölçüdə qalır. 👁️",
    "Hər yerdə yer üzündə istilik adalıdır — şəhərlər kəndlərdən istidirlər. 🏙️",
    "Əqərb mavi rəng görmür. 🦂",
    "Yer kürəsindəki bütün qumu saymaq üçün min il lazımdır. 🏖️",
    "Dünyanın ən uzun çayı Nil çayı — 6650 km. 🌊",
    "İnsanda 639 əzələ var. 💪",
    "Fıl yalnız dörd heyvan arasında — insanla birlikdə özünü tanıyır. 🐘",
    "Qurd 40 km məsafədən qoxu hiss edə bilir. 🐺",
    "Kiçik Sahara çölü bütün ABŞ-dan böyükdür. 🏜️",
    "İnsan ömrü boyunca ortalama 70 il yatır. 😴",
    "Göy qurşağının içindəki rənglər 7 yox, qeyri-müəyyən sayda ola bilər. 🌈",
    "Okean zəlzələlərinin 90%-i Sakit Okean ətrafında baş verir. 🌊",
    "Xüsusi növlü yumurta 1000 ilə qədər saxlana bilir. 🥚",
    "Gürcüstan dünyanın şərabın vətənidir — 8000 il tarixi var. 🍷",
    "NASA-nın internetinin sürəti 91 Gbps-dir. 🌐",
    "İnsanlığın tarixi boyunca yazılmış kitabların sayı 130 milyondan çoxdur. 📚",
    "Dünyanın ən uzun sözü islandiya dilindədir — 189 hərf. 📝",
]

MOTIVATIONAL_QUOTES = [
    "Uğur əməyin mükafatıdır. 💪",
    "Böyük işlər kiçik addımlarla başlar. 🚶",
    "Çətin olmayan heç nə dəyərli deyil. 🎯",
    "Hər gün dünəndən daha yaxşı ol. 📈",
    "Düşən baş deyil, qalmayan baş uduzur. 💡",
    "Ümid itməyincə, hər şey mümkündür. 🌟",
    "Başlamaq işin yarısıdır. ✅",
    "Zəhmət meyvəsiz qalmaz. 🌳",
    "İstəyən nail olar, tənbəl hər zaman bəhanə tapar. 🏆",
    "Hər çətin an sənin güclənmə fürsətindir. 💪",
    "Uğurlu insan düşdüyü yerə deyil, qalxdığına baxır. 🔝",
    "Özünə inan, çünki başqaları sənin inanmağını gözləyir. ✨",
    "Dünya böyük arzuların önünə keçə bilməz. 🌍",
    "Qorxu sənin ən böyük düşmənin, cəsarət ən böyük dostundur. 🦁",
    "Hər gün yeni bir başlanğıcdır. 🌅",
    "Heç vaxt çox gec deyil — bu gün başla. ⏰",
    "Uğurun sirrı: heç vaxt tərk etməmək. 🔑",
    "Böyük rüzgar böyük dirəkdən eşilir. 🌪️",
    "Yer üzündə mümkünsüz olan yalnız çalışmamağın mükafatıdır. 🏅",
    "Ağlayan uşaq süd alır, ağlamayan aclıqdan ölür. 🍼",
    "Əvvəl özünü sev, sonra başqalarını. ❤️",
    "Gözəl gələcək bu günkü əziyyətin mükafatıdır. 🌈",
    "İnsan ümidi ilə güclüdür. 💫",
    "Qalxmayan düşməz — amma qalxan da düşməz. ⬆️",
    "Hər çətinliyə görə həll yolu var. 🔓",
    "Sən düşündüyündən daha güclüsün. 💪",
    "Xeyirxah adam özü də xoşbəxtdir. 😊",
    "Mütaliə etmək insanı dünyanın sahibi edir. 📖",
    "Uşaqlıqda öyrənilən elm daş üzərindəki oyma kimidir. 🪨",
    "Yaxşı başlanğıc işin yarısıdır. 🎬",
    "Bilmək istəmək — bilmənin başlanğıcıdır. 🎓",
    "Nə əkərsən, onu biçərsən. 🌾",
    "Böyük arzular böyük əziyyət tələb edir. 🌠",
    "Hər insan özünün ən böyük düşmənidir. 🪞",
    "Bir gün deyil, bu gün. 📅",
    "Heç bir uğur tərk etməklə qazanılmır. 🏆",
    "Güc fiziki yox, ruhi ölçülür. 🧠",
    "Hər başarı hekayəsi bir iradə hekayəsidir. 💡",
    "Yalnız irəliyə baxmaq müvəffəqiyyəti gətirir. 🔭",
    "Sevdiyin işi et, heç vaxt işlə yorulmayacaqsan. 🎨",
    "Öyrənmək heç vaxt bitmir. 📚",
    "İnsan bildiyi qədər azaddır. 🕊️",
    "Gözəl yuxular gözəl əməllərlə qazanılır. ⭐",
    "Sənin taleyini yalnız sən yazırsın. ✍️",
    "Keçmişə baxma, gələcəyi planla. 🗓️",
    "Güclü iradi olan hər çətinliyi aşar. 🧗",
    "Sən etməsən kim edəcək? 🤔",
    "Sabah deyil, indi vaxtıdır. ⏱️",
    "Öz nöqtənə çat — başqasının yolunda deyilsən. 🗺️",
    "İstəklər əzmkarlıqla gerçəkləşir. 🌟",
    "Özünü kəşf etmək ən böyük səyahətdir. 🧭",
    "Şikayət etmə, çözüm ara. 🔧",
    "Cəhd etməyən heç vaxt yoxlanmaz. 🎲",
    "Bir günlük zəhmət ömürlük fəxrdir. 🏅",
    "Ümidini itirmə, yolu itirmə. 🛤️",
    "Başarı heç vaxt qəzadan gəlmir. 🎯",
    "Güclü insan öz problemini həll edəndir. 🛠️",
    "Nə edəcəksənsə, yaxşı et. 👑",
    "Uçmaq istəyirsənsə, torpağa bağlanma. 🦅",
    "Azlıq qorxusu çoxluq cəsarəti doğurur. ⚔️",
    "Hər insan öz qəhrəmanı ola bilər. 🦸",
    "Zəhmətsiz ləzzət olmaz. 🍎",
    "Dünya gözəldir, onu seyrə çıx. 🌏",
    "Bir güldən bağça olmaz, amma bir güldən başlanır. 🌺",
    "Xəyal qur, sonra çalış. 💭",
    "Hər gün bir şey öyrən. 📖",
    "Ağlın sənin ən qiymətli sərvətindir. 💎",
    "Cəsarət yalnız qorxmamaq deyil, qorxub irəliləməkdir. 🦁",
    "İnsan öyrəndiyi qədər böyüyür. 🌱",
    "Sən istəsən hər şeyi dəyişdirə bilərsən. ⚡",
    "Sabah haqqında qeyd et, bu gün haqqında hərəkət et. 📝",
    "Əməl etmək arzulamaqdan güclüdür. 💥",
    "Hər insan fərqlidir — bu sənin gücündür. 🌈",
    "Nə qədər çox öyrənsən, bir o qədər çox bilmədiyin üzə çıxır. 🔬",
    "Sən bu dünyaya bir şey verməyə gəlmisən. 🎁",
    "Hər mənfi düşüncəni müsbətə çevir. ➕",
    "Özünə inanmayan kimsə sənə inanmayacaq. 🪞",
    "Güclü insan başqasına kömək etməkdən zövq alır. 🤝",
    "Hər gün sənin şansındır. 🎰",
    "Yorulsan da dayanma — yavaşla, amma dayanma. 🐢",
    "Hər çətin dönəm bir öyrənmə fürsətidir. 📚",
    "Öz yerini tap, dünyaya buradan bax. 🗼",
    "Böyük arzular böyük insan yetirir. 🌟",
    "İnsan öldüğündə nə buraxdığına baxırlar. ⭐",
    "Gözəl söz qapı açar. 🗝️",
    "Mütəvazillik böyüklüyün nişanəsidir. 🙏",
    "Sən hər gün daha güclü olursun. 💪",
    "Bugün etdiklərın sabahını müəyyənləşdirir. 🌅",
    "Bir addım at, yolun özü görünəcək. 👣",
    "Hər uğursuzluq yeni bir başlanğıcdır. 🔄",
    "Xoşbəxtlik seçimdir. 😊",
    "Sevgi həyatın ən böyük motivasiyasıdır. ❤️",
    "Həyat sürprizdir — hər günü dəyərləndir. 🎁",
    "Birlikdə daha güclüyük. 🤝",
    "Qürurla başla, sevgiylə bitir. 🌟",
    "Sən düşündüyündən çox şeyə qadirsin. 🚀",
    "Hər şey öyrənilir — yalnız cəsarət lazımdır. 🎓",
    "Yaxşı insan hər yerdə işıq saçar. ✨",
]

LOVE_QUOTES = [
    "Sevgi insanı dəyişdirir, lakin özü dəyişməz. ❤️",
    "Sevmək öyrənilmir, sadəcə olur. 💕",
    "Sevgi baxışdan başlar, ürəkdə bitər. 👀❤️",
    "Həqiqi sevgi sözsüz anlaşmadır. 💬❤️",
    "Sənin gülüşün mənim ən sevimli musiqidir. 🎶",
    "Sevgi olmadan həyat nə rənglidir, nə də mənalı. 🌈",
    "Sən mənim ən gözəl xəyalımsan. 💭❤️",
    "Bir ürəyin ikiyə bölünməsi: sən oradasan mən burada. 💞",
    "Sevgi iki nəfər arasındaki görünməz körpüdür. 🌉",
    "Sənin yanında olmaq evdə olmaq kimidir. 🏠❤️",
    "Məhəbbət nə mesafə tanıyır, nə də zaman. ⏳❤️",
    "Sən mənim ürəyimin ən gözəl guşəsindəsən. 💖",
    "Sevgi verdiyimiz qədər artır. 💝",
    "Sənin gözlərindən bütün dünyam görünür. 👁️❤️",
    "Ürəyim yalnız sənin adını bilir. 💗",
    "Sən olmasan həyat bir rəng az olardı. 🎨",
    "Sevgi çılğınlıqdır — ən gözəl çılğınlıq. 🌹",
    "Sənin gülüşün hər kədərimi aparan rüzgardır. 🌬️😊",
    "Həqiqi sevgi zamanla güclənir. ⏰❤️",
    "Sənin yanında vaxt uçur. ⏱️💕",
    "Sən mənim güncü sahilimisən. 🏖️❤️",
    "Sevgi sözlə deyil, hərəkətlə sübut edilir. 💪❤️",
    "Sənin yadına düşəndə gülümsəyirəm. 😊💕",
    "Sevgi insanı yüngülləşdirir. 🕊️",
    "Sən mənim bütün əskikliklərimi tamamlayırsan. 🧩❤️",
    "Sevmək ən böyük cəsarətdir. 🦁❤️",
    "Sənin adın ürəyimdə oyulub. 💓",
    "Sevgi olmasa həyat nə mənası olan bir seyrdən ibarət olar. 🌙",
    "Sən mənim həyatıma rəng qatdın. 🌈❤️",
    "Həqiqi sevgi şərt tanımaz. ✅❤️",
    "Sən mənim hər günümə xoşbəxtlik gətirirsən. ☀️",
    "Sevgi insanı güclü edir. 💪💕",
    "Sənin yanında olmaq dünyanın ən gözəl şeyidir. 🌍❤️",
    "Ürəyim sənin üçün daha sürətli döyünür. 💗",
    "Sən mənim ulduzumsan. ⭐❤️",
    "Sevgi vermək almaqdır. 🔄❤️",
    "Sən mənim sevincimin qaynağısan. 😊💕",
    "Həyat səninsiz yarımçıqdır. 💔➡️💖",
    "Sənin gülüşü günəş doğması kimidir. 🌅😊",
    "Sevgi ürəkdə deyil, ürək boyudur. 💖",
    "Sən mənim ən gözəl sürprizimisən. 🎁❤️",
    "Həqiqi sevgi başqasının xoşbəxtliyini istəməkdir. 😊❤️",
    "Sən yanımda olanda hər şey yaxşıdır. ✨",
    "Sevgi insanı yetkinləşdirir. 🌱❤️",
    "Sən mənim ürəyimin sahibisən. 🗝️💖",
    "Ömrümün ən gözəl səhifəsi səninlə olan günlərdir. 📖❤️",
    "Sənin adın duam oldu. 🙏❤️",
    "Sevgi paylaşıldıqca çoxalır. 💕➡️💞",
    "Sən mənim ən dəyərli xəzinəmsən. 💎❤️",
    "Həqiqi sevgi hər şeye dözür. 💪❤️",
    "Sənin yanında ağlamaq da gözəldir. 😢❤️",
    "Sevgi zamanı durdurandır. ⏸️❤️",
    "Sənin hər anın mənim üçün qiymətlidir. ⏳💕",
    "Ürəyimdəki ən böyük yer sənin üçündür. 💖",
    "Sən mənim güçdə güc, zəiflikdə sığınacağımsan. 🏰❤️",
    "Sevgi dərin suya bənzəyir — altını görmək olmur. 🌊❤️",
    "Sən mənim həyat şeirimisən. 📝❤️",
    "Həqiqi sevgi mesafə tanımır. 🌍❤️",
    "Sən mənim ürəyimin mahnısısan. 🎵❤️",
    "Sevgi ikinin birlikdə böyüməsidir. 🌱🌱",
    "Sən olmayan yerdə boşluq olur. 🕳️❤️",
    "Sənin yanında olmaq hər zaman əvəzsizdir. 💕",
    "Sevgi zamanla deyil, ürəklə ölçülür. ❤️",
    "Sənin gözlərindəki işıq məni yönləndirir. 👁️✨",
    "Həqiqi sevgi iki ruhun birləşməsidir. 🔗❤️",
    "Sən mənim ən gözəl hissimsən. 💭❤️",
    "Sevgi olmadan dünya soyuq bir yer olardı. 🌨️❤️",
    "Sənin adını eşidəndə ürəyim coşur. 💓",
    "Həqiqi sevgi incitmədən sevməkdir. 🕊️❤️",
    "Sən mənim ömrümün ən gözəl fəslisən. 🍂🌸❄️☀️",
    "Sevgi iki insanı bir edər. 👫❤️",
    "Sənin yanında anlar əbədilik kimi keçir. ⏳💕",
    "Həqiqi sevgi yalnız bir insanla mümkündür. 💑",
    "Sən mənim ürəyimdəki ən parlaq işıqsan. 💡❤️",
    "Sevgi sözsüz əlaqədir. 🤫❤️",
    "Sən mənim hər sübhim, hər gecəm. 🌅🌙",
    "Həqiqi sevgi özgəliyə qiymət verməkdir. 💎❤️",
    "Sən mənim qəlbimin sahibisən. 🔐❤️",
    "Sevgi könüllü köləlikdir. 🔗❤️",
    "Sənin yanında olmaq istəmirəm, olmalıyam. 💕",
    "Həqiqi sevgi daim böyüyür. 🌱❤️",
    "Sən mənim ən böyük bəxtəvərliyimisən. 🍀❤️",
    "Sevgi zamanı gözəlləşdirir. ⏳✨",
    "Sən mənim hər anımın mənasısan. 💕",
    "Həqiqi sevgi sözdən çox hərəkətdir. ❤️💪",
    "Sən mənim güncüm, anam, sevgilim, yoğumsun. 💖",
    "Sevgi özgəliyə güvənməkdir. 🤝❤️",
    "Sən mənim ən yaxın insanımsan. 👫❤️",
    "Həqiqi sevgi cəhənnəmə belə gedər. 🔥❤️",
    "Sən mənim bütün dünyamsın. 🌍❤️",
    "Sevgi sən olduqda başlayır. 💗",
    "Sən mənim həyatımın ən böyük hədiyyəsisən. 🎁❤️",
    "Həqiqi sevgi ürəyə işıq salar. 💡❤️",
    "Sən mənim ən gözəl xəyalım, ən güzəl gerçəyimsən. 💭✨❤️",
    "Sevgi güzgüdə deyil, gözlərdə görünür. 👁️❤️",
    "Sən mənim həyatımın ən ağıllı seçimisən. 🧠❤️",
    "Həqiqi sevgi sonsuz səbirdir. ⏳❤️",
    "Sən mənim ürəyimdəki ən gözəl xatirəmsən. 📸❤️",
]

RIDDLES = [
    {"q": "Nə var ki, dalıb çıxarsan, özündə var, amma görünmür? 🤔", "a": "Cavab: Nəfəs. 💨"},
    {"q": "Su içər, amma su olmaz; od götürər, amma od olmaz. Bu nədir? 🤔", "a": "Cavab: Bulud. ☁️"},
    {"q": "Hər kəsin var, amma heç kim görmür. Bu nədir? 🤔", "a": "Cavab: Gələcək. 🔮"},
    {"q": "Dalın olmaz, içi olmaz, amma hər şey onda var. Bu nədir? 🤔", "a": "Cavab: Güzgü. 🪞"},
    {"q": "Yeyər, amma ağzı yoxdur; içər, amma doymaz. Bu nədir? 🤔", "a": "Cavab: Torpaq. 🌱"},
    {"q": "Qaçar, amma ayağı yoxdur; danışar, amma dili yoxdur. Bu nədir? 🤔", "a": "Cavab: Çay. 💧"},
    {"q": "Gündüzlər yatar, gecələr oyaq olar. Bu nədir? 🤔", "a": "Cavab: Ulduz. ⭐"},
    {"q": "Nə qədər yesən, bir o qədər artır. Bu nədir? 🤔", "a": "Cavab: Açlıq. 😋"},
    {"q": "Qapısı yox, pəncərəsi yox, amma içindədir. Bu nədir? 🤔", "a": "Cavab: Yumurta. 🥚"},
    {"q": "Üzər, amma balıq deyil; uçar, amma quş deyil. Bu nədir? 🤔", "a": "Cavab: Təyyarə. ✈️"},
    {"q": "Soyunduqca böyüyür. Bu nədir? 🤔", "a": "Cavab: Soğan. 🧅"},
    {"q": "Ağı var, amma ağlamaz; dili var, amma danışmaz. Bu nədir? 🤔", "a": "Cavab: Kitab. 📚"},
    {"q": "Gecə gəlir, gündüz gedir. Bu nədir? 🤔", "a": "Cavab: Yuxu. 😴"},
    {"q": "Hər kəs içinə girir, amma kimsə çıxmır. Bu nədir? 🤔", "a": "Cavab: Zaman. ⏰"},
    {"q": "Həm isti, həm soyuq, həm nəmli, həm quru olar. Bu nədir? 🤔", "a": "Cavab: Hava. 🌤️"},
    {"q": "Biri var, biri yox — amma hər ikisi eyni vaxtda var. Bu nədir? 🤔", "a": "Cavab: Gündüz və gecə. 🌓"},
    {"q": "Əl ilə tutmaq olmur, ağıl ilə tutmaq olar. Bu nədir? 🤔", "a": "Cavab: Fikir. 💭"},
    {"q": "Nə qədər yeyilərsə, bir o qədər böyüyür. Bu nədir? 🤔", "a": "Cavab: Yanğın. 🔥"},
    {"q": "Hər gün doğulur, hər gecə ölür. Bu nədir? 🤔", "a": "Cavab: Günəş. ☀️"},
    {"q": "Bütün dünyanı görür, amma özünü görə bilmir. Bu nədir? 🤔", "a": "Cavab: Göz. 👁️"},
    {"q": "Qanadı var, amma uçmur; ayağı var, amma qaçmır. Bu nədir? 🤔", "a": "Cavab: Saat. ⏰"},
    {"q": "Sonu yox, əvvəli yox, amma ortası var. Bu nədir? 🤔", "a": "Cavab: Dairə. ⭕"},
    {"q": "Yüz yaşına girər, amma heç vaxt böyüməz. Bu nədir? 🤔", "a": "Cavab: İl. 📅"},
    {"q": "Hər şeyi bilir, amma özü heç nə demir. Bu nədir? 🤔", "a": "Cavab: Ensiklopediya. 📖"},
    {"q": "İçi var, çölü yox. Bu nədir? 🤔", "a": "Cavab: Deşik. 🕳️"},
    {"q": "Yandırır, amma od deyil; isitmir, amma istiyə oxşayır. Bu nədir? 🤔", "a": "Cavab: Biber. 🌶️"},
    {"q": "Hər evdə var, amma görünmür. Bu nədir? 🤔", "a": "Cavab: Hava. 💨"},
    {"q": "Düz gedər, amma qapı tapmaz. Bu nədir? 🤔", "a": "Cavab: Işıq. 💡"},
    {"q": "Kimsə üstünə oturmur, amma hər kəs onun üstündədir. Bu nədir? 🤔", "a": "Cavab: Torpaq. 🌍"},
    {"q": "Saç var, amma başı yox; dal var, amma bədəni yox. Bu nədir? 🤔", "a": "Cavab: Mısır. 🌽"},
    {"q": "Gündüz olar, gecə yox olur. Bu nədir? 🤔", "a": "Cavab: Kölgə. 🌑"},
    {"q": "Hər kəsə lazımdır, amma heç kəs almır. Bu nədir? 🤔", "a": "Cavab: Sağlıq. 💚"},
    {"q": "Böyük ağacdan kiçik şey. Bu nədir? 🤔", "a": "Cavab: Yaprak. 🍃"},
    {"q": "Qaçar, dayanar, amma ayağı yoxdur. Bu nədir? 🤔", "a": "Cavab: Saat əqrəbi. ⏱️"},
    {"q": "Hər gün görünür, amma tutmaq olmur. Bu nədir? 🤔", "a": "Cavab: Günəş. ☀️"},
    {"q": "Dişi var, amma ısırmaz. Bu nədir? 🤔", "a": "Cavab: Daraq. 🪮"},
    {"q": "Qapısı var, amma evi yox. Bu nədir? 🤔", "a": "Cavab: Çanta. 👜"},
    {"q": "Ağlar, amma gözü yox. Bu nədir? 🤔", "a": "Cavab: Bulud. ☁️"},
    {"q": "Uçar, amma qanadı yox. Bu nədir? 🤔", "a": "Cavab: Vaxt. ⏳"},
    {"q": "Söyləsən yox olar. Bu nədir? 🤔", "a": "Cavab: Sirr. 🤫"},
    {"q": "Hər gün böyür, amma canlı deyil. Bu nədir? 🤔", "a": "Cavab: Çuxur. 🕳️"},
    {"q": "Şirin olur, amma nə meyva, nə şirniyyat. Bu nədir? 🤔", "a": "Cavab: Yuxu. 😴"},
    {"q": "Min il yaşar, amma nəfəs almaz. Bu nədir? 🤔", "a": "Cavab: Daş. 🪨"},
    {"q": "Girər, çıxmaz; çıxar, girməz. Bu nədir? 🤔", "a": "Cavab: Tüstü. 💨"},
    {"q": "Quru yerdə üzər. Bu nədir? 🤔", "a": "Cavab: Kölgə. 🌑"},
    {"q": "İki ayağı var, amma yeriyə bilmir. Bu nədir? 🤔", "a": "Cavab: Pərgar. 📐"},
    {"q": "Həm sənin, həm mənim, amma ikimiz birlikdə tutamırıq. Bu nədir? 🤔", "a": "Cavab: Ad. 🏷️"},
    {"q": "Yüz ildir yatır, amma yuxusu yoxdur. Bu nədir? 🤔", "a": "Cavab: Qaya. 🪨"},
    {"q": "Yaxınlaşdıqca uzaqlaşır. Bu nədir? 🤔", "a": "Cavab: Üfüq. 🌅"},
    {"q": "Açarı yox, qapısı var. Bu nədir? 🤔", "a": "Cavab: Ağız. 👄"},
    {"q": "Hamı alır, amma heç kim almır. Bu nədir? 🤔", "a": "Cavab: Nəfəs. 💨"},
    {"q": "Yeyiləndə böyüyür, içiləndə kiçilir. Bu nədir? 🤔", "a": "Cavab: Atəş. 🔥"},
    {"q": "İçi dolu, çölü boş. Bu nədir? 🤔", "a": "Cavab: Qoz. 🥜"},
    {"q": "Hamı onu bilir, heç kim görüb bilmir. Bu nədir? 🤔", "a": "Cavab: Allah. 🙏"},
    {"q": "Yazda doğulur, qışda ölür. Bu nədir? 🤔", "a": "Cavab: Yarpaq. 🍂"},
    {"q": "Nə hiss edər, nə görər, amma hamı ona baxar. Bu nədir? 🤔", "a": "Cavab: Rəsm. 🖼️"},
    {"q": "Üstü var, altı var, amma ortası yox. Bu nədir? 🤔", "a": "Cavab: Üzük. 💍"},
    {"q": "Yeriyər, amma yolu yoxdur. Bu nədir? 🤔", "a": "Cavab: Vaxt. ⏳"},
    {"q": "Hər gün yuyulur, amma temizlenmez. Bu nədir? 🤔", "a": "Cavab: Su. 💧"},
    {"q": "Hər evdə var, amma heç kimə satılmır. Bu nədir? 🤔", "a": "Cavab: Işıq. 💡"},
    {"q": "Özü qaçmaz, amma hamını qaçırar. Bu nədir? 🤔", "a": "Cavab: Qorxu. 😱"},
    {"q": "Nə ağlar, nə gülər, amma hər şeyi bilir. Bu nədir? 🤔", "a": "Cavab: Kitab. 📚"},
    {"q": "Gün olar, min olar, amma biri olar. Bu nədir? 🤔", "a": "Cavab: İl. 📅"},
    {"q": "Hər kəs güvənir, amma görmür. Bu nədir? 🤔", "a": "Cavab: Hava. 💨"},
    {"q": "Hər kəsin var, amma istifadə etmir. Bu nədir? 🤔", "a": "Cavab: Beyni. 🧠"},
    {"q": "Günəş çıxanda yox olur, gecə çıxanda görünür. Bu nədir? 🤔", "a": "Cavab: Ulduzlar. ⭐"},
    {"q": "Kiçik olur, amma hamının diqqətini çəkir. Bu nədir? 🤔", "a": "Cavab: Almas. 💎"},
    {"q": "Özü yatmır, başqasını yatırır. Bu nədir? 🤔", "a": "Cavab: Mahnı. 🎵"},
    {"q": "Hər kəs geyir, amma kimsə görə bilmir. Bu nədir? 🤔", "a": "Cavab: Yaş. 🔢"},
    {"q": "Yeməz, amma acıqar. Bu nədir? 🤔", "a": "Cavab: Mədə xəstəliyi. 🤢"},
    {"q": "Ağır olmaz, amma hamını əzər. Bu nədir? 🤔", "a": "Cavab: Kədər. 😢"},
    {"q": "Hər gün artır, amma kimsə yığmır. Bu nədir? 🤔", "a": "Cavab: Yaş. 🎂"},
    {"q": "Başqa yerdə olmadan eyni yerdə qalar. Bu nədir? 🤔", "a": "Cavab: Güzgü əksi. 🪞"},
    {"q": "Min addım atar, amma bir addım getmər. Bu nədir? 🤔", "a": "Cavab: Dəyirman. ⚙️"},
    {"q": "Gözəl olmur, amma hamı onu istər. Bu nədir? 🤔", "a": "Cavab: Pul. 💰"},
    {"q": "Yağmur yağar, o islanmaz. Bu nədir? 🤔", "a": "Cavab: Su. 💧"},
    {"q": "İki qardaş var, bir-birini görə bilmirlər. Bu nədir? 🤔", "a": "Cavab: Gözlər. 👁️"},
    {"q": "Özü hərəkət etmir, amma hamı onu hərəkət etdirir. Bu nədir? 🤔", "a": "Cavab: Yol. 🛤️"},
    {"q": "Ölür, amma hamı onu yeyir. Bu nədir? 🤔", "a": "Cavab: Şam. 🕯️"},
    {"q": "Qış gəlir, o ərir; yay gəlir, o donur. Bu nədir? 🤔", "a": "Cavab: Oda. ❄️"},
    {"q": "İçinə girib çıxa bilmirsən, amma hər kəs gedir. Bu nədir? 🤔", "a": "Cavab: Yuxu. 😴"},
    {"q": "Hamı görür, amma kimsə almır. Bu nədir? 🤔", "a": "Cavab: Göy üzü. 🌌"},
    {"q": "Beş qardaş bir evdə yaşayır. Bu nədir? 🤔", "a": "Cavab: Barmaqlar. 🖐️"},
    {"q": "Hər gün bir az ölür, amma yenə yaşayır. Bu nədir? 🤔", "a": "Cavab: Şam. 🕯️"},
    {"q": "Bulud olur, yağmur olur, çay olur, dəniz olur. Bu nədir? 🤔", "a": "Cavab: Su. 💧"},
    {"q": "Hər kəsdə bir əl, amma heç kim istifadə etmir. Bu nədir? 🤔", "a": "Cavab: Saat əqrəbi. ⏰"},
    {"q": "Özü xırda, amma bütün dünyanı işıqlandırır. Bu nədir? 🤔", "a": "Cavab: Ulduz. ⭐"},
    {"q": "Böyüklər görür, uşaqlar görə bilmir. Bu nədir? 🤔", "a": "Cavab: Gələcək. 🔮"},
    {"q": "Heç nəyə bənzəmir, amma hər şeyə bənzədir. Bu nədir? 🤔", "a": "Cavab: Güzgü. 🪞"},
    {"q": "Qolu yox, amma hamısını qucaqlayır. Bu nədir? 🤔", "a": "Cavab: Dəniz. 🌊"},
    {"q": "Hər kəsin yanında, amma kimsənin deyil. Bu nədir? 🤔", "a": "Cavab: Kölgə. 🌑"},
    {"q": "Dünyanın ən uzun nədir? 🤔", "a": "Cavab: Ömür. ⏳"},
    {"q": "Hamını bilir, amma özü haqqında heç nə bilmir. Bu nədir? 🤔", "a": "Cavab: Lüğət. 📖"},
    {"q": "Hər gün doğulur, heç vaxt böyümür. Bu nədir? 🤔", "a": "Cavab: Bu gün. 📅"},
    {"q": "Saysız qardaşı var, amma atası yoxdur. Bu nədir? 🤔", "a": "Cavab: Dalğa. 🌊"},
    {"q": "Hamının var, kimsə vermir. Bu nədir? 🤔", "a": "Cavab: Ad. 🏷️"},
]
