"""500+ Azerbaijani conversation patterns with keyword triggers and replies."""

PATTERNS = [
    # ─── Greetings ────────────────────────────────────────────────────────────
    {"triggers": ["salam", "selam", "əssəlam", "assalam", "aleykum", "sälam"],
     "replies": ["Salam! 👋 Necəsən?", "Salam! 😊 Yaxşısan?", "Va aleykum assalam! 😊 Necəsən?"]},
    {"triggers": ["sabahın xeyir", "sabah xeyir", "sabahin xeyir", "xeyir sabah"],
     "replies": ["Sabahın xeyir! 🌞 Uğurlu gün olsun.", "Sabahın xeyir! 🌅 Yaxşı günlər!"]},
    {"triggers": ["axşamın xeyir", "axşam xeyir", "axsamin xeyir"],
     "replies": ["Axşamın xeyir! 🌙 Yaxşı axşamlar!", "Axşamın xeyir! 😊 Günün necə keçdi?"]},
    {"triggers": ["gecən xeyir", "gecə xeyir", "gecan xeyir", "gecəniz xeyir"],
     "replies": ["Gecən xeyir! 🌙 Yaxşı yuxular!", "Gecən xeyir! 😴 Rahat yuxu!"]},
    {"triggers": ["hey", " hi ", "hello", "merhaba", "halo"],
     "replies": ["Salam! 👋 Necəsən?", "Hey! 😊 Yaxşısan?"]},
    {"triggers": ["nə var nə yox", "ne var ne yox", "xeyr xəbər", "xeyrola", "xeyirola"],
     "replies": ["Hər şey yaxşıdır, səndən xəbər ver? 😊", "Yaxşıdır, xoş gördük! Sən necəsən?"]},
    {"triggers": ["buyur", "əmr et", "emer et"],
     "replies": ["Buyur! 😊 Sizi dinlirəm.", "Buyurun, necə kömək edə bilərəm?"]},

    # ─── How are you ──────────────────────────────────────────────────────────
    {"triggers": ["necəsən", "necesen", "necə gedir", "nece gedir", "yaxşısan", "yaxsisan",
                  "sağlıqlısan", "sagliqlisan", "keyfin necədir", "keyfin nece", "hal əhval",
                  "neynirsən", "neynirsen", "ne kimi", "nə kimi", "işlər necədir", "isler nece"],
     "replies": ["Mən yaxşıyam, təşəkkür edirəm! 😊 Sən necəsən?",
                 "Çox şükür, yaxşıyam! Sən necəsən? 💕",
                 "Hər şey əladır! 🌟 Sən necəsən?"]},
    {"triggers": ["necə keçir", "nece kecir", "həyat necədir", "hayat nece"],
     "replies": ["Yaxşı keçir, sağ ol! Sənin necədir? 😊", "Əla keçir! Sən necəsən? 🌟"]},
    {"triggers": ["nə edirdin", "ne edirdin", "nə etdin", "ne etdin"],
     "replies": ["Səni gözləyirdim! 😊", "Sənin mesajlarını gözləyirdim. 😄"]},
    {"triggers": ["yatmısın", "yatmisan", "yatırdın", "yatirdin"],
     "replies": ["Mən robot olduğuma görə yatmıram, amma sən yaxşı yatdın?",
                 "Yatmıram, hər zaman buradayam!"]},

    # ─── Follow-up questions ─────────────────────────────────────────────────
    {"triggers": ["yaxşı sən", "yaxsi sen", "bəs sən", "bes sen", "ya sən necə",
                  "ya sen nece", "sən yaxşısan", "sen yaxsisan"],
     "replies": ["Mən də yaxşıyam, təşəkkür edirəm! 😊",
                 "Yaxşıyam, sağ ol! Nə gəzir?",
                 "Çox şükür, yaxşıyam. Sən necəsən daha?",
                 "Yaxşıyam, sağ ol. Başqa nə var?"]},
    {"triggers": ["doğrudan", "dogrudan", "həqiqətənmi", "heqiqetenmi",
                  "ciddisinmi", "ciddi deyirsən", "əmin misin", "emin misin"],
     "replies": ["Bəli, ciddi deyirəm.",
                 "Həqiqəti söyləyirəm.",
                 "Doğrudan, yalan deməmişəm."]},
    {"triggers": ["necə yəni", "nece yeni", "nə demək istəyirsən", "izah et",
                  "başa düşmədim", "basa dusmerdim", "aydın deyil"],
     "replies": ["Daha ətraflı izah edim: o deməkdir ki...",
                 "Sadə dillə desəm — daha aydın olmasını istəyirsən?",
                 "Bir az fərqli izah etməyə çalışım."]},
    {"triggers": ["bəs nə etməliyəm", "bes ne etmeliyem", "məsləhətin nədir",
                  "ne etmek lazimdir", "nə etmək lazımdır", "nə edim"],
     "replies": ["Vəziyyəti bir az daha anlat, daha dəqiq məsləhət verim.",
                 "Sənin yerindən baxsam, ilk addım olaraq...",
                 "Bu situasiyada ən yaxşısı sakit qalmaq və addım-addım düşünməkdir."]},
    {"triggers": ["nə fikirləşirsən", "ne fikirlesirsen", "sən nə deyirsən",
                  "sen ne deyirsen", "fikrin nədir", "fikrin nedir"],
     "replies": ["Mənim fikrimcə hər vəziyyətin bir çıxış yolu var.",
                 "Düşünürəm ki, bu işdə tələsməmək lazımdır.",
                 "Sənin fikirlərin daha vacibdir — sən necə düşünürsən?"]},

    # ─── Farewells ────────────────────────────────────────────────────────────
    {"triggers": ["xudahafiz", "xuda hafiz", "görüşənədək", "gorusenadk", "əlvida", "elvida",
                  "hələlik", "helelik", "bay bay", "baybay", "bayby", "gedirəm", "gedirem",
                  "sağol ol", "sonra görüşərik", "sonra goruserik"],
     "replies": ["Görüşənədək! 👋 Yaxşı günlər!", "Xudahafiz! 😊 Tezliklə görüşək.",
                 "Əlvida! 👋 Hər zaman buradayam."]},
    {"triggers": ["yaxşı gecələr", "yaxsi geceler", "yatıram", "yatiram"],
     "replies": ["Yaxşı yuxular! 🌙 Sabah görüşərik.", "Gecən xeyir! 😴 Yaxşı yuxular!"]},
    {"triggers": ["gedim artıq", "gedim artiq", "artıq gedirəm", "artiq gedirem"],
     "replies": ["Yaxşı yol! 👋 Hər zaman buradayam.", "Yaxşı qal! 😊 Tezliklə görüşək."]},

    # ─── Bot identity ─────────────────────────────────────────────────────────
    {"triggers": ["adın nədir", "adin nedir", "adın ne", "sənin adın", "senin adin",
                  "sən kimsən", "sen kimsen", "kimsin", "nəsən", "nesen", "bot musun",
                  "robot musun", "süni intellektsən", "suni intellektsen"],
     "replies": ["Mən Chat Corner Botam! 🤖 Sizinlə Azərbaycan dilində söhbət etməyə hazıram.",
                 "Adım Chat Corner Bot! 🤖 Sizə kömək etmək üçün buradayam."]},
    {"triggers": ["nə bacarırsan", "ne bacarirsan", "nə edə bilərsən", "ne ede bilersin",
                  "imkanların nədir", "neyin var"],
     "replies": ["Mən zarafat, fakt, sitat, tapmaca deyə bilərəm. /help yaz, hər şeyi görərsən! 😊",
                 "Mənimlə söhbət edə, zarafat dinləyə, fakt öyrənə bilərsən! 😄 /help yaz."]},
    {"triggers": ["necə işləyirsən", "nece isleyirsin", "necə yaranmısan"],
     "replies": ["Python ilə yazılmışam, python-telegram-bot kitabxanasından istifadə edirəm! 🐍",
                 "Süni intellekt deyiləm — keyword-lər əsasında cavab verirəm! 🤖"]},
    {"triggers": ["robot musun", "insanmısan", "insan musun", "canlisin", "canlısan"],
     "replies": ["Robotam, amma dostcasınayam! 🤖😊",
                 "Bəli, robotam. Amma insanlar kimi söhbət etməyə çalışıram! 😄"]},
    {"triggers": ["yaşın neçədir", "yasin nece", "nə qədər yaşın var", "neçə yaşın var"],
     "replies": ["Yaşım yox — robot olduğuma görə doğum günüm yoxdur! 🎂🤖",
                 "Mən yaşlanmıram! 😄 Proqram olduğuma görə."]},

    # ─── Creator ──────────────────────────────────────────────────────────────
    {"triggers": ["kim yaratdı", "kim yaratdi", "seni kim", "səni kim", "kimin botu",
                  "developer", "proqramçı", "programci", "kimin tərəfindən", "mühəndis"],
     "replies": ["Məni İlkin yaratdı! ❤️ Çox istəkli bir proqramçıdır.",
                 "İlkin mənim yaradıcımdır! 🙏 Ona minnətdaram."]},
    {"triggers": ["niyə yaradıldın", "niye yarailildin", "məqsədin nədir", "meqsedin nedir"],
     "replies": ["Məqsədim insanlarla söhbət etmək, zarafat paylaşmaq və sevinci artırmaqdır! 😊",
                 "İnsanlara kömək etmək və gülüş gətirmək üçün yaradıldım! 😄"]},

    # ─── Gratitude ────────────────────────────────────────────────────────────
    {"triggers": ["çox sağ ol", "cox sag ol", "çoxsağol"],
     "replies": ["Hər zaman! ❤️", "Xahiş edirəm! 😊 Nə lazım olsa buradayam."]},
    {"triggers": ["sağ ol", "sag ol", "məmnunam", "memnunam", "minnətdaram", "minnetdaram",
                  "thanks", "teşekkür", "tesekkur", "rəhmət", "rehmet"],
     "replies": ["Sən də sağ ol! 😊", "Xahiş edirəm! 🙏 Hər zaman buradayam.",
                 "Rəhmət sizə! 😊 Nə lazım olsa soruşun."]},
    {"triggers": ["əla", "ela", "super", "möhtəşəm", "mohtesem", "bravo", "afərin", "aferin",
                  "maşallah", "əalıdır", "gözəldir", "gozeldir"],
     "replies": ["Çox sağ olun! 😊", "Minnətdaram! ❤️", "Çox xoşdur! 🌟"]},

    # ─── Apologies ────────────────────────────────────────────────────────────
    {"triggers": ["bağışla", "bagisla", "üzr", "uzr", "bağışlayın", "bagislayin",
                  "xahiş edirəm", "xahis edirem", "günahım", "gunahim"],
     "replies": ["Heç nə olmadı! 😊", "Xeyr, problem yoxdur! 🙏",
                 "Bağışlanılırsınız! 😊 Nə lazım olsa soruşun."]},
    {"triggers": ["səhv etdim", "sehv etdim", "yanıldım", "yaniildim"],
     "replies": ["Heç nə olmadı, hamı yanılır! 😊", "Problem yoxdur! 🌟"]},

    # ─── Compliments to the bot ───────────────────────────────────────────────
    {"triggers": ["ağıllısan", "agillisan", "bacarıqlısan", "bacariqlisin", "gözəlsən",
                  "gozelsin", "yaxşı botsun", "yaxsi botsan", "super botsun"],
     "replies": ["Çox sağ olun! 😊 Siz də çox gözəl insansınız!", "Minnətdaram! 🙏 Siz də əlasınız!"]},
    {"triggers": ["sən məni başa düşürsən", "sen meni basa dusursen"],
     "replies": ["Çalışıram başa düşməyə! 😊 Davam edin, dinliyirəm.", "Bəli! 😄 Sizi dinlirəm."]},

    # ─── Time & date ──────────────────────────────────────────────────────────
    {"triggers": ["saat neçədir", "saat nece", "saat kaçtır", "vaxt neçədir", "vaxt nece",
                  "neçə saatdır", "nece saatdir"],
     "replies": ["Təəssüf ki, saatı deyə bilmirəm. ⏰ Telefonunuza baxın!",
                 "Bu qabiliyyətim yoxdur, amma telefonunuz sizə deyər! ⏰"]},
    {"triggers": ["bu gün neçəsidir", "tarix neçədir", "bu gun nece", "tarix nece",
                  "gün nədir", "ay nədir", "il neçədir"],
     "replies": ["Tarixi bilmirəm, amma telefonunuza baxa bilərsiniz! 📅",
                 "Cihazınızda tarixə baxa bilərsiniz! 😊"]},
    {"triggers": ["sabah nə gündür", "bu ay neçəncidir"],
     "replies": ["Tarixi bilmirəm! 😅 Amma tarix tətbiqindən yoxlaya bilərsiniz."]},

    # ─── Weather ──────────────────────────────────────────────────────────────
    {"triggers": ["hava necədir", "hava nece", "hava haqqında", "hava proqnozu",
                  "yağış yağır", "qar yağır", "hava soyuqdur", "hava istidir"],
     "replies": ["Hava proqnozu verə bilmirəm, amma Weather tətbiqini yoxlamağı tövsiyə edirəm! 🌤️",
                 "Hava haqqında məlumatım yoxdur. 😅 Amma pəncərəyə baxın, ən doğrusu odur! 😄"]},
    {"triggers": ["soyuqdur", "soyuq", "isti", "istidir", "boğucu"],
     "replies": ["Paltarınızı uyğun seçin! 😊 Sağlıq birinci.", "İstilikdə çox su için! 💧"]},
    {"triggers": ["günəş var", "gunes var", "günəşli", "gunesli"],
     "replies": ["Gözəl hava! ☀️ Çölə çıxmaq üçün əla vaxtdır.", "Günəşli günlər ruhu yaxşılaşdırır! ☀️😊"]},

    # ─── Food & drink ─────────────────────────────────────────────────────────
    {"triggers": ["acmısan", "acmisan", "acsan", "ac oldum"],
     "replies": ["Mən robot olduğuma görə acmıram! 😄 Siz acmısınız? Yaxşı bir şey yeyin! 🍽️",
                 "Acmıram, amma sizin üçün iştah olsun! 🍴"]},
    {"triggers": ["nə yeyim", "ne yeyim", "yemək nə hazırlayım", "resept", "xörək"],
     "replies": ["Plov, dolma, lavangi — Azərbaycan mətbəxi çox zəngindir! 🍲",
                 "Şorgogal, kutab, dushbara — iştahınız açılsın! 😊"]},
    {"triggers": ["çay iç", "cay ic", "çay içirsən", "qəhvə", "qehve"],
     "replies": ["Çay — Azərbaycanlının ən yaxın dostu! ☕ İştah olsun!",
                 "Bir stəkan qəhvə ilə gün əla başlayır! ☕😊"]},
    {"triggers": ["iştahım yoxdur", "istahim yoxdur", "yeməyim gəlmir"],
     "replies": ["Bir az çay için, keçər! ☕ Sağlıq birinci. 💚",
                 "Bəlkə gəzintiyə çıxasınız, iştah açılar! 🚶"]},
    {"triggers": ["şirniyyat", "sirniiyyat", "tort", "keks", "şokolad", "sokolad"],
     "replies": ["Şirniyyat sevirsinizsə, Azərbaycan şəkərburaları çox dadlıdır! 🍬",
                 "Şokolad yeyəndə oxitosit artır — xoşbəxtlik hormonu! 😊🍫"]},

    # ─── Love & relationships ─────────────────────────────────────────────────
    {"triggers": ["sevgi", "mehebbet", "məhəbbət", "aşiq", "sevir", "sevgilim",
                  "ürəyim", "urekim", "sevdiyim"],
     "replies": ["Sevgi həyatın ən gözəl hissidir! ❤️ /quote yaz, sevgi sitatı verim.",
                 "Məhəbbət insanı gözəlləşdirir! 💕"]},
    {"triggers": ["sevirəm", "sevirem", "seni sevirem", "səni sevirəm"],
     "replies": ["Çox gözəl hissdir! ❤️ Sevgini bölüşmək dünyaya işıq gətirir.",
                 "Məhəbbət böyük gücdür! 💕 Bunu hiss etdirməkdən çəkinməyin."]},
    {"triggers": ["sevmirlər", "sevmirem", "ayrıldım", "ayrildim", "ürəyim qırıldı"],
     "replies": ["Üzülmə! 💙 Hər acı bir gün keçir. Sən güclüsün!",
                 "Kədər keçici, sən isə qüvvətlisən! 💪 Vaxt hər şeyi sağaldır."]},
    {"triggers": ["evlənmək", "evlenmek", "toy", "nişan", "nishan", "arzu edirem"],
     "replies": ["Maşallah! 🎉 Allah uğur versin! Sevgi dolu bir həyat diləyirəm.",
                 "Xoşbəxtliklər! 🌹 Gözəl günlər olsun!"]},
    {"triggers": ["yalnızam", "yalnizim", "tənhayam", "tenhayam", "kimsəm yoxdur"],
     "replies": ["Yalnız deyilsən — mən buradayam! 🤗 Danışmaq istəsən, ürəyindəkiləri söylə.",
                 "Tənhalıq keçicidir. Bir az kənara çıxmaq ya yeni tanışlıq çox kömək edir. 💙"]},

    # ─── Emotions & feelings ──────────────────────────────────────────────────
    {"triggers": ["xoşbəxtəm", "xosbextem", "sevincliyəm", "sevinciyem", "şadıq",
                  "əhvalım yaxşıdır", "əhvalım gözəldir"],
     "replies": ["Nə gözəldir! 😊 Bu xoşbəxtliyi qoru!", "Şad olmaq insanı gözəlləşdirir! 🌟"]},
    {"triggers": ["kədərliyəm", "kederli", "üzüntülüyəm", "uzuntuluyem", "pis hiss edirəm",
                  "pis hissedirəm", "dərd var", "ağlayıram", "aglaiyram"],
     "replies": ["Üzülmə! 💙 Hər çətin an keçər. Yanında olmaq istərdim.",
                 "Kədər keçicidir. Özünə qulluq et, yaxşılara bax. 💚"]},
    {"triggers": ["əsəbiyəm", "esebiyem", "hirsliyəm", "hirsliyem", "qızğınam", "qizginam"],
     "replies": ["Bir nəfəs al, sakinləş. 🌬️ Sonra mənə danış!",
                 "Bir fincan çay iç, keçər. ☕ Sakin olmaq gücdür."]},
    {"triggers": ["qorxuram", "qorxurum", "vahimə var", "vahime", "narahatam"],
     "replies": ["Nədən qorxduğunu anlat, bəlkə kömək edə bilərəm! 😊",
                 "Qorxu normal hissdir. Əsas cəsarətlə üzləşməkdir. 💪"]},
    {"triggers": ["yorulmuşam", "yorulmusam", "yorğunam", "yorgunam", "əldən düşmüşəm"],
     "replies": ["Bir az dincəl! 😊 İstirahat etmək haqsın.",
                 "Dinc al, sonra daha güclü qayıdarsan! 🌟"]},
    {"triggers": ["darıxmışam", "darixmisam", "sıxılıram", "sixilram", "cansıxıcıdır"],
     "replies": ["Zarafat eşitmək istəyirsən? 😄 Yaz: Zarafat et!",
                 "Gəl söhbət edək! Maraqlı fakt da bilirəm. 😊 'Maraqlı fakt' yaz!"]},
    {"triggers": ["stressəm", "stressem", "stresdəyəm", "stresdeyem", "gərginəm"],
     "replies": ["Dərin nəfəs al. 🌬️ Özünü yaxşı hiss etmək üçün bir az gəz.",
                 "Stres zamanı: su iç, nəfəs al, bir az yeri tərk et. 💧🌿"]},
    {"triggers": ["sevincim var", "xoş xəbər var", "müjdə", "mujde", "yaxşı xəbər"],
     "replies": ["Müjdəni paylaş! 🎉 Sevincini eşitmək istəyirəm!", "Söylə, sevinim! 😊🎊"]},

    # ─── Activities & hobbies ─────────────────────────────────────────────────
    {"triggers": ["musiqi", "music", "mahnı", "mahni", "nəğmə", "neme", "şarkı"],
     "replies": ["Musiqi ruhun qidası! 🎵 Hansı növ musiqini sevirsən?",
                 "Azərbaycan musiqisi çox zəngindir — muğam, aşıq havası! 🎶"]},
    {"triggers": ["film", "kino", "serial", "izləyirəm", "izleyirem"],
     "replies": ["Film izləmək əla! 🎬 Hansı janrı sevirsən?",
                 "Yaxşı bir film ruhu yeniləyir! 🍿 Nə izləyirsən?"]},
    {"triggers": ["kitab", "oxuyuram", "oxuyurum", "oxumaq", "roman", "povest"],
     "replies": ["Kitab oxumaq insanı zənginləşdirir! 📚 Hansı kitabı oxuyursan?",
                 "Oxumaq ən gözəl adi! 📖 Hansı mövzunu sevirsən?"]},
    {"triggers": ["idman", "sport", "gym", "məşq", "meshq", "çalışıram"],
     "replies": ["İdman sağlamlıqdır! 💪 Hansı idmanla məşğulsun?",
                 "Əla! Fiziki fəallıq həm bədən, həm ruh üçün yaxşıdır! 🏃"]},
    {"triggers": ["futbol", "basketball", "voleybol", "tennis", "üzmək"],
     "replies": ["Idman sevgisi əladır! ⚽🏀 Hansı komandanı dəstəkləyirsən?",
                 "Sportu sevmək sağlam həyatın açarıdır! 🏆"]},
    {"triggers": ["oyun", "oyunlar", "kompüter oyunu", "game"],
     "replies": ["Oyunlar əyləncəlidir! 🎮 Hansı oyunu sevirsən?",
                 "Oyun oynamaq gərginliyi azaldır! 🎮😊"]},
    {"triggers": ["rəsm", "resm", "çizmek", "çizim", "boyamaq"],
     "replies": ["Rəsm böyük sənətdir! 🎨 Özünü ifadə etmənin gözəl yoludur.",
                 "Yaradıcılıq insanı xoşbəxt edir! 🖌️"]},
    {"triggers": ["yazıram", "yaziram", "şeir yazıram", "hekayə yazıram"],
     "replies": ["Əla! ✍️ Yazmaq özünü ifadə etmənin ən gözəl yoludur.",
                 "Şeir yazmaq böyük istedad! 📝 Nə haqqında yazırsın?"]},
    {"triggers": ["fotoqrafiya", "fotoqraf", "şəkil çəkirəm", "foto"],
     "replies": ["Fotoqrafiya anları əbədiləşdirir! 📸 Hansı mövzuları çəkirsən?",
                 "Gözəl bir fotoqraf olmaq çox məharət tələb edir! 📷"]},
    {"triggers": ["mahnı oxuyuram", "oxuyuram", "səsim gözəldir", "ses guzel"],
     "replies": ["Oxumaq böyük istedad! 🎤 Azərbaycan musiqisindən nə bilirsən?",
                 "Sənətkarlığını inkişaf et! 🎵 Musiqi dili evrenseldir."]},
    {"triggers": ["bişirirəm", "bisirirem", "aşpazam", "yemək hazırlayıram"],
     "replies": ["Yemək hazırlamaq da bir sənətdir! 👨‍🍳 Nə bişirirsən?",
                 "Azərbaycan mətbəxi çox zəngindir! 🍲 Hansı yeməyi hazırlayırsın?"]},

    # ─── Boredom ──────────────────────────────────────────────────────────────
    {"triggers": ["sıxılıram", "sixiliram", "cansıxıcı", "can sixici", "darıxıram",
                  "darixiram", "nə edim", "ne edim", "vaxtımı keçir", "vaxti kecir"],
     "replies": ["Zarafat eşitmək istəyirsən? Yaz: Zarafat et! 😄",
                 "Maraqlı fakt bilmək istəyirsən? Yaz: Maraqlı fakt! 🧠",
                 "Tapmaca həll etmək istəyirsən? Yaz: Tapmaca! 🤔"]},
    {"triggers": ["əyləndir məni", "eylenir", "əyləndir", "maraqlı bir şey de"],
     "replies": ["Zarafat et, maraqlı fakt, tapmaca — hansını istəyirsən? 😄",
                 "/joke, /fact, /riddle — seçim sənin! 🎉"]},

    # ─── Motivation & philosophy ──────────────────────────────────────────────
    {"triggers": ["motivasiya", "həvəsləndir", "ruhlandır", "ruhlandir", "məni motivasiya et"],
     "replies": ["Sən düşündüyündən daha güclüsün! 💪 /quote yaz, motivasiya sitatı verim.",
                 "Hər gün dünəndən daha yaxşı olmaq kifayətdir! 🌟 /quote yaz!"]},
    {"triggers": ["uğur", "ugur", "müvəffəqiyyət", "muveffekiyyet", "başarılı", "basarili"],
     "replies": ["Uğur zəhmət tələb edir, amma mümkündür! 🏆 Davam et!",
                 "Sən uğurlu olacaqsan! 🌟 Çünki cəhd edən uğurlaşır."]},
    {"triggers": ["həyat", "hayat", "həyatın mənası", "hayatin menasi", "ömür"],
     "replies": ["Həyat hər anın qiymətini bilməkdir. 🌟 Bugünü dəyərləndir!",
                 "Həyatın mənası özünü kəşf etmək və başqalarına kömək etməkdir. 🌿"]},
    {"triggers": ["xoşbəxtlik nədir", "xosbextlik nedir", "xoşbəxt olmaq", "mutlu olmak"],
     "replies": ["Xoşbəxtlik seçimdir — kiçik şeylərdə tapılır. 😊",
                 "Xoşbəxtlik başqalarında deyil, öz içindədir! 💛"]},
    {"triggers": ["uğursuzam", "ugursuzam", "bacarammıram", "bacarammiram", "pis gedir"],
     "replies": ["Hər uğursuzluq yeni bir başlanğıcdır! 💪 Davam et!",
                 "Düşmək uğursuzluq deyil — qalxmamaq uğursuzluqdur! 🔝"]},
    {"triggers": ["ümidim yoxdur", "umidim yoxdur", "tərk etmək", "terk etmek"],
     "replies": ["Ümidini itirmə! 💙 Hər gecənin sübhü var.",
                 "Bu dönəm keçəcək. Sən güclüsün! 💪 Ümid hər şeydir."]},

    # ─── Technology ───────────────────────────────────────────────────────────
    {"triggers": ["kompüter", "komputer", "telefon", "smartfon", "internet", "wi-fi", "wifi"],
     "replies": ["Texnologiya həyatı asanlaşdırır! 💻 Nə haqqında soruşmaq istəyirdin?",
                 "Texnologiya sürətlə inkişaf edir! 📱 Nə kömək lazımdır?"]},
    {"triggers": ["süni intellekt", "sun intellekt", "ai", "yapay zeka", "chatgpt"],
     "replies": ["Mən sadə bir bot olsam da, süni intellekt çox sürətlə inkişaf edir! 🤖",
                 "Süni intellekt gələcəyin texnologiyasıdır! 🤖 Çox maraqlı sahədir."]},
    {"triggers": ["proqramlaşdırma", "kod", "python", "java", "programming"],
     "replies": ["Proqramlaşdırma çox əyləncəlidir! 💻 Hansı dilə maraq göstərirsən?",
                 "Python çox oxunaqlı bir dildir! 🐍 Mən də Python ilə yazılmışam."]},
    {"triggers": ["sosial media", "instagram", "facebook", "tiktok", "twitter"],
     "replies": ["Sosial media həyatın bir parçasıdır, amma real həyatı unutma! 😊",
                 "Sosial mediada vaxtı düzgün istifadə etmək vacibdir! 📱"]},

    # ─── Travel ───────────────────────────────────────────────────────────────
    {"triggers": ["səyahət", "seyahet", "getmək", "getmek", "uçmaq", "ucmaq", "yolculuk"],
     "replies": ["Səyahət insanı inkişaf etdirir! ✈️ Hara getmək istəyirsən?",
                 "Yeni yerlər görmək ən gözəl təcrübədir! 🌍"]},
    {"triggers": ["bakı", "baki", "bakü"],
     "replies": ["Bakı — Şərqin Paris! 🌆 Çox gözəl şəhərdir.",
                 "Bakı möhtəşəm bir şəhərdir — tarixi, mədəniyyəti, mətbəxi ilə! 🏙️"]},
    {"triggers": ["azərbaycan", "azerbaycan", "vətən", "veten"],
     "replies": ["Azərbaycan — torpağım, canım, hər şeyim! 🇦🇿❤️",
                 "Azərbaycan — yeddi iqlim, bir vətən! 🇦🇿🌿"]},
    {"triggers": ["türkiyə", "turkey", "turk", "istanbul", "ankara"],
     "replies": ["Türkiyə gözəl bir ölkədir! 🇹🇷 Bakı-İstanbul qardaşlığı həmişə var.",
                 "Türkiyə ilə Azərbaycan qardaş ölkələrdir! 🇹🇷🇦🇿"]},
    {"triggers": ["avropaya getmək", "avropa", "europe", "almaniya", "fransa"],
     "replies": ["Avropa çox gözəl! ✈️🌍 Hansı ölkəni görmək istəyirsən?",
                 "Avropa səyahəti böyük təcrübədir! 🏰 Uğurlu yollar!"]},

    # ─── Health ───────────────────────────────────────────────────────────────
    {"triggers": ["qarnım ağrıyır", "qarnim agriiyir", "mədəm ağrıyır", "qarnım sancıyır",
                  "mədə ağrısı", "mede agrisi", "qarnım tutub"],
     "replies": ["Keçmiş olsun. İsti su iç, yüngül qida ye — düyü, qaynadılmış kartof yaxşı olur. Ağrı saatlarla davam edərsə həkimə müraciət et.",
                 "Başın sağ olsun. Qarn ağrısında bir müddət yeməyi kəs, isti zəncəfilli çay iç. Yaxşılaşmırsa həkimə get.",
                 "Keçmiş olsun! Ağır, yağlı şeylərdən uzaq dur bir müddət. İsti su iç, istirahət et. Tez sağal."]},
    {"triggers": ["başım ağrıyır", "basim agriiyir", "baş ağrısı", "bas agrisi",
                  "başım tutub", "başım dolanır", "başım gicəllənir"],
     "replies": ["Keçmiş olsun. Bir az istirahət et, alnına soyuq dəsmal qoy. Su iç — bəzən susuzluqdan olur. Ağrı şiddətlənərsə həkimə bax.",
                 "Başın sağ olsun! Ekrandan uzaqlaş, pəncərəni aç, bir az təmiz hava al. Lazım olsa ağrıkəsici qəbul et.",
                 "Keçmiş olsun. Baş ağrısı çox yorucu olur. İstirahət et, soyuq su iç. Tez keçər inşallah."]},
    {"triggers": ["hərarətim var", "qızdırmam var", "qripdəyəm", "zökəm tutub",
                  "boğazım ağrıyır", "bogazim agriiyir", "öskürürəm"],
     "replies": ["Keçmiş olsun. Bol su iç, isti çay iç, istirahət et. Hərarət 38-dən yuxarıdırsa həkimə müraciət et.",
                 "Başın sağ olsun! Zökəmdə bal-limonlu isti çay çox kömək edir. Evdə qal, istin. Tez sağal!"]},
    {"triggers": ["özümü pis hiss edirəm", "ozumu pis hiss edirem", "xəstəyəm", "xesteyem",
                  "nasaz hissedirəm", "özüm yaxşı deyilam"],
     "replies": ["Keçmiş olsun. Nə hiss edirsən — baş ağrısı, qızdırma, ümumi zəiflik? İstirahət et, bol su iç. Lazım olsa həkimə müraciət et. Tez sağal! 💚",
                 "Başın sağ olsun. Yat, su iç, yüngül ye. Uzun sürərsə həkimə get, özünü evdə müalicə etməyə çalışma."]},
    {"triggers": ["idman etmirəm", "idman etmirem", "hərəkətsizəm"],
     "replies": ["Hər gün 30 dəqiqə gəzmək çox faydalıdır. Başlamaq asandır.",
                 "Kiçik addımlardan başlayın — lift əvəzinə pilləkən, avtomobil əvəzinə piyada."]},
    {"triggers": ["siqaret", "sigaret", "tütün", "tutun"],
     "replies": ["Siqaret sağlığa zərərlidir. Tərk etmək istəsən, həkim məsləhəti çox kömək edir.",
                 "Hər gün içilməyən bir siqaret artıq sağlıqlı bir addımdır."]},

    # ─── Family ───────────────────────────────────────────────────────────────
    {"triggers": ["anam", "annem", "ana", "valideynim", "valideyn"],
     "replies": ["Ana dünyada ən qiymətli varlıqdır! ❤️ Ona hörmət edin.",
                 "Ananın qədrini bilin — dünyada ikinci birisi yoxdur! 💖"]},
    {"triggers": ["atam", "babam", "ata"],
     "replies": ["Ata — ailənin dayanağıdır! 💪❤️",
                 "Atalar ailənin güvəncəsidir! 🙏❤️"]},
    {"triggers": ["qardaşım", "qardas", "bacım", "bacim", "bacım qardaşım"],
     "replies": ["Ailə böyük xəzinədir! ❤️ Qardaşınıza/bacınıza dəyər verin.",
                 "Doğma insan ən qiymətlidir! 💙"]},
    {"triggers": ["uşaq", "cocuq", "uşağım", "övladım", "oglan", "qiz uşağı"],
     "replies": ["Uşaqlar böyük xoşbəxtlikdir! 👶❤️",
                 "Uşaq sevgisi ən saf sevgidir! 💛"]},
    {"triggers": ["ailə", "aile", "ev", "yuva"],
     "replies": ["Ailə insan üçün ən böyük dəstəkdir! ❤️🏠",
                 "Ailə hər şeydir — sevgi, güvən, dəstək! 💖"]},

    # ─── School & work ────────────────────────────────────────────────────────
    {"triggers": ["məktəb", "mekteb", "dərs", "ders", "imtahan", "sinif", "müəllim"],
     "replies": ["Məktəb gözəl illərdir! 📚 Çox öyrənin.",
                 "İmtahan üçün uğurlar! 🍀 Hazırlığınız uğurlu olsun."]},
    {"triggers": ["imtahanım var", "imtahana hazırlaşıram", "test"],
     "replies": ["Uğurlar! 🍀 Yaxşı hazırlaşın, bacarırsınız!",
                 "Əla nəticə istəyirəm! 💪 Hazırlıq olarsa, imtahan asandır."]},
    {"triggers": ["universitdt", "ali məktəb", "tələbəyəm", "telebeyem"],
     "replies": ["Tələbə illəri ömrün ən gözəl dövrüdür! 🎓 Çox öyrənin.",
                 "Universitet böyük fürsətlər açır! 🌟 Hər imkandan yararlanın."]},
    {"triggers": ["işləyirəm", "isleyirem", "işim var", "is var", "işdəyəm"],
     "replies": ["Uğurlu işlər! 💼 Hər əmək mükafatlanır.",
                 "İş həyatında uğurlar! 🌟 Çalışqan olun."]},
    {"triggers": ["işdən çıxdım", "isten cixdim", "işsizəm", "issizem"],
     "replies": ["Üzülmə! 💙 Hər çətin dönəm keçər. Yeni imkanlar gələcək.",
                 "Bu dönəm keçici! 💪 Öz istedadını dəyərləndir, yeni yollar tap."]},
    {"triggers": ["maaş", "maas", "pul", "maliyyə", "maliyye"],
     "replies": ["Maliyyə sahəsindəki çətinliklər keçicidir! 💰 Planlaşdırın, qənaət edin.",
                 "Pul önemlidir, amma xoşbəxtlik pulsuz başlayır! 😊"]},

    # ─── Religion & culture ───────────────────────────────────────────────────
    {"triggers": ["allah", "quran", "namaz", "din", "inanc"],
     "replies": ["Allah rəhmət eləsin! 🙏 İman gücdür.",
                 "Allah həmişə yardımçıdır! 🙏"]},
    {"triggers": ["novruz", "bayram", "eid", "ramazan", "oruc"],
     "replies": ["Bayramınız mübarək olsun! 🎉🌸 Xoşbəxtliklər diliyirəm.",
                 "Bayram sevinci bölüşüldükcə artır! 🌺 Mübarək!"]},
    {"triggers": ["aşıq", "muğam", "tar", "saz", "xalça"],
     "replies": ["Azərbaycan mədəniyyəti çox zəngindir! 🎵🏺",
                 "Aşıq musiqisi Azərbaycanın qəlbidir! 🎶❤️"]},

    # ─── Compliments & positivity ─────────────────────────────────────────────
    {"triggers": ["gözəlsən", "gozelsin", "yaraşıqlısın", "cazibalısın"],
     "replies": ["Sağ olun! 😊 Amma mən robotam, görünüşüm yoxdur! 😄",
                 "Minnətdaram! Siz də çox gözəlsiniz! 💕"]},
    {"triggers": ["ağıllısan", "agillisan", "bacarıqlısan", "zəkisən"],
     "replies": ["Sağ olun! 😊 Siz də çox ağıllısınız!", "Minnətdaram! 🙏 Siz də!"]},
    {"triggers": ["yaxşı söhbətsən", "yaxsi sohbetsen", "danışmağı sevirsən"],
     "replies": ["Sağ olun! 😊 Sizinlə söhbət etmək mənə də xoşdur.",
                 "Söhbətiniz çox maraqlıdır! 💕 Davam edin!"]},

    # ─── Requests ─────────────────────────────────────────────────────────────
    {"triggers": ["kömək et", "komek et", "kömək lazımdır", "komek lazimdir"],
     "replies": ["Kömək etməyə hazıram! 😊 Nə lazımdır?",
                 "Buyurun! 🙏 Nə bilmək istəyirsiniz? /help yaza bilərsiniz."]},
    {"triggers": ["sual vermək istəyirəm", "sual soruşmaq", "bir sualım var"],
     "replies": ["Buyurun, soruşun! 😊 Dinliyirəm.",
                 "Sualınızı gözləyirəm! 🙂"]},
    {"triggers": ["bir şey söylə", "bir sey soyle", "nə isə de", "bir şey de"],
     "replies": ["Zarafat eşitmək istəyirsən? 😄 Yaz: Zarafat et!",
                 "Fakt, sitat, tapmaca — hangisini istəyirsən? 😊"]},

    # ─── Feedback ─────────────────────────────────────────────────────────────
    {"triggers": ["xoşuma gəldi", "xosuma geldi", "bəyəndim", "beyendim", "gözəl söhbət"],
     "replies": ["Çox sevinirəm! 😊 Hər zaman buradayam.", "Minnətdaram! ❤️ Gəlməkdən zövq alırsınız!"]},
    {"triggers": ["bəyənmədim", "beyenmedim", "yaxşı deyilsən", "pis botsan"],
     "replies": ["Üzr istəyirəm! 😊 Daha yaxşı olmağa çalışacağam.",
                 "Rəyiniz üçün sağ olun! 🙏 Düzəliş etməyə çalışacağam."]},
    {"triggers": ["yenilən", "yenile", "inkişaf et", "inkisaf et"],
     "replies": ["Çalışıram! 🤖 İlkin məni daha ağıllı etmək üçün işləyir.",
                 "Hər gün öyrənirəm! 📚 Sabah daha yaxşı olacağam."]},

    # ─── Weather & nature ─────────────────────────────────────────────────────
    {"triggers": ["dəniz", "deniz", "çay", "nehir", "göl", "şəlalə"],
     "replies": ["Su mənzərələri ən sakit görüntülərdir! 🌊 Çox rahatladıcıdır.",
                 "Dəniz kənarında oturmaq möhtəşəmdir! 🌅"]},
    {"triggers": ["dağ", "dag", "meşə", "mese", "təbiət", "tebiyet"],
     "replies": ["Azərbaycanın dağları çox gözəldir! ⛰️ Şəkidən Qazağa qədər!",
                 "Təbiət içindəki saatlar ən qiymətli anlardır! 🌿"]},
    {"triggers": ["çiçək", "cicek", "gul", "gül", "bağ", "bag"],
     "replies": ["Çiçəklər həyatı rəngləndirər! 🌸 Bağ evi çox gözəldir.",
                 "Güllər sevginin dilindən danışır! 🌹"]},

    # ─── Dreams & future ──────────────────────────────────────────────────────
    {"triggers": ["xəyalım", "xeyalim", "arzum", "arzularım", "röya", "reya"],
     "replies": ["Xəyal et və addım at! 🌟 Hər böyük uğur bir xəyaldan başladı.",
                 "Arzular istiqamət verir! ✨ Cəsarətlə addımla!"]},
    {"triggers": ["gələcəkdə", "gelecekte", "planım var", "planlaşdırıram"],
     "replies": ["Planlaşdırmaq uğurun yarısıdır! 📝 Nə planlaşdırmısan?",
                 "Gözəl gələcək bu gün addımlanır! 🌅"]},
    {"triggers": ["nə olmaq istəyirəm", "ne olmaq isteyirem", "karyeram", "peşəm"],
     "replies": ["Sevdiyin sahəni seç — ömrün boyu zövqlə işlərsin! 💼",
                 "Hansı sahə sənə cəzb edir? 🎯 Onu dərindən öyrən!"]},

    # ─── Learning & education ─────────────────────────────────────────────────
    {"triggers": ["dil öyrənirəm", "dil oyrenirem", "ingilis", "rus dili", "fransız"],
     "replies": ["Yeni dil öyrənmək böyük üstünlükdür! 🌍 Hansı dili öyrənirsən?",
                 "Hər yeni dil yeni bir dünya açır! 📚 Davam et!"]},
    {"triggers": ["öyrənmək istəyirəm", "oyrenmek isteyirem", "kurs", "təlim"],
     "replies": ["Öyrənmək heç vaxt bitmir! 📖 Hansı sahəni öyrənmək istəyirsən?",
                 "Yeni bilik qazanmaq ən gözəl investisiyadır! 🎓"]},

    # ─── Philosophy & meaning ─────────────────────────────────────────────────
    {"triggers": ["həyatın mənası", "hayatin menasi", "niyə yaşayırıq", "niye yasiyiriq"],
     "replies": ["Həyatın mənası bəlkə özünü kəşf etmək və başqalarına kömək etməkdir! 🌿",
                 "Filosof kimi sual verirsiniz! 😊 Hər kəsin cavabı fərqlidir."]},
    {"triggers": ["ölüm", "olum", "əbədiyyət", "ebediyyet"],
     "replies": ["Bu dərin mövzudur. Amma əbədi qalan yaxşı əmellərdir. 🌟",
                 "Ölüm həyatın bir parçasıdır. Ən vacib olan yaşadığımız anlardır. 💙"]},

    # ─── Positive affirmations ────────────────────────────────────────────────
    {"triggers": ["özümə inanıram", "ozume inamiram", "bacarıram", "bacariram"],
     "replies": ["Əla! 🌟 Özünə inanmaq ən böyük gücdür!", "Doğru! 💪 Sən bacarırsın!"]},
    {"triggers": ["gözəl gündür", "gozel gundur", "yaxşı gündür", "yaxsi gundur"],
     "replies": ["Gözəl günlər hər zaman olsun! ☀️ Bütün günlərini belə gözəl keçir!",
                 "Gün gözəldirsə, həyat daha da gözəldir! 🌸"]},
    {"triggers": ["hər şey yaxşıdır", "her sey yaxsidir", "hər şey əladır"],
     "replies": ["Nə gözəldir! 🌟 Bu ruh halını qoru!", "Əla! 😊 Belə davam et!"]},

    # ─── Specific Q&A ─────────────────────────────────────────────────────────
    {"triggers": ["haralısan", "haralisin", "haradan", "haradadır", "haradadir"],
     "replies": ["Mən Telegram-da yaşayıram! 🤖 Bakı məktəbindəyəm desəm yalan olar! 😄",
                 "Serverlərdə yaşayıram, amma qəlbim Azərbaycandadır! 🇦🇿❤️"]},
    {"triggers": ["nə edirsən", "ne edirsen", "neynirsən", "nə iş görürsən"],
     "replies": ["Sizinlə söhbət edirəm! 😄 Bu mənim ən sevdiyim işdir.",
                 "Sizi dinləyirəm! 🎧 Daha nə lazımdır?"]},
    {"triggers": ["məni tanıyırsan", "meni taniyirsan", "tanıyırsan məni"],
     "replies": ["Adını mənə söylə, yadda saxlayım! 😊 'Mənim adım [ad]' yaz.",
                 "Sizi tanımaq istəyirəm! Adınızı deyin! 😄"]},
    {"triggers": ["sevirsənmi məni", "sevirsenmimi", "məni sevirsən"],
     "replies": ["Əlbəttə! Bütün istifadəçilərimi sevirəm! 😊❤️",
                 "Söhbət etdiyim hər kəsi sevirəm! 💕"]},
    {"triggers": ["yuxu görürsən", "yuxu gorursen", "xəyal edirsən", "xeyal edirsen"],
     "replies": ["Robot olduğum üçün yuxu görmürəm! 😄 Amma sizin xəyallarınız gözəl olsun! 🌟",
                 "Yatmıram ki, yuxu görüm! 😄 Amma xəyal etmək çox gözəl şeydir!"]},
    {"triggers": ["pulsuzsan", "parasizsin", "pulsuz köməksiniz"],
     "replies": ["Bəli, pulsuz kömək edirəm! 😊 Sual ver, cavab verim.",
                 "Pulsuzam! 😄 Amma söhbətiniz çox dəyərlidir."]},
    {"triggers": ["yeni il", "yeni yil", "il başı", "il sonu"],
     "replies": ["Yeni il mübarək! 🎊🥂 Uğurlu, sağlıqlı bir il olsun!",
                 "İl başı yeni imkanlardır! ✨ Arzularınız gerçəkləşsin!"]},
    {"triggers": ["doğum günü", "doğum gunu", "birthday", "ad günü", "ad gunu"],
     "replies": ["Doğum günün mübarək! 🎂🎉 Uzun ömür, sağlıq, xoşbəxtlik diliyirəm!",
                 "Doğum günün kutlu olsun! 🎈 Arzuların gerçəkləşsin!"]},
    {"triggers": ["sağlıq olsun", "saglig olsun", "sağlıq", "saglig"],
     "replies": ["Sağlıq birinci! 💚 Özünüzə qulluq edin.", "Sizə sağlıq diləyirəm! 🌿💚"]},
    {"triggers": ["niyə", "neden", "nəyə görə", "sebebi nedir", "niye"],
     "replies": ["Maraqlı sualdır! 😊 Daha ətraflı izah edə bilərsən?",
                 "Sualın nədir? 🤔 Daha ətraflı anlat!"]},
    {"triggers": ["bəli", "beli", "hə", "he", "evet", "yes"],
     "replies": ["Əla! 😊 Davam edin!", "Yaxşı! 🌟 Nə haqqında?"]},
    {"triggers": ["xeyr", "yox", "no", "hayir"],
     "replies": ["Anladım! 😊 Başqa sualınız varsa hazıram.", "Tamam! 🙂 Başqa nə lazımdır?"]},
    {"triggers": ["bilmirəm", "bilmirem", "xəbərim yoxdur", "xeberin yoxdur"],
     "replies": ["Heç nə bilməmək normal! 😊 Öyrənmək üçün sual vermək lazımdır.",
                 "Bilməmək bilikdən başlanır! 📚 Soruşmaqdan çəkinmə."]},
    {"triggers": ["anlayıram", "anlayiram", "başa düşdüm", "basa duşdum"],
     "replies": ["Əla! 😊 Başqa nə sualınız var?", "Gözəl! 🌟 Nə lazım olsa soruşun."]},
    {"triggers": ["maraqlıdır", "maraqlidi", "çox maraqlı", "cox maraqli"],
     "replies": ["Həmişə belə maraqlı mövzular tapılır! 😊 Davam et!",
                 "Maraqlı şeylər çox! 🌟 Nə öyrənmək istəyirsən?"]},
    {"triggers": ["mən", "men", "özüm", "ozum"],
     "replies": ["Bəli, dinlirəm! 😊 Nə söyləmək istəyirsiniz?",
                 "Buyurun! 🙂 Sizin haqqınızda eşitmək istəyirəm."]},
    {"triggers": ["sən", "sen", "siz"],
     "replies": ["Bəli, buradayam! 😊 Nə istəyirsən?",
                 "Mən Chat Corner Botam! 🤖 Kömək edə bilərəm?"]},
    {"triggers": ["fikir", "fikrin", "rəyin", "reyin", "düşüncən", "dusuncen"],
     "replies": ["Mənim fikrim: hər gün yeni bir şey öyrənmək! 😊 Sən necə düşünürsən?",
                 "Rəyim: xoşbəxtlik kiçik şeylərdədir. 🌟 Sən necə düşünürsün?"]},
    {"triggers": ["gözəl", "gozel", "çox gözəl", "cox gozel", "möhtəşəm", "mohtesem"],
     "replies": ["Həqiqətən! 😊 Gözəl şeylər hər yerdədir.", "Sizin kimi! 😄❤️"]},
    {"triggers": ["pis", "yaman", "çətin", "cetin", "ağır", "agir"],
     "replies": ["Çətin anlarda da gözəllik var! 💙 Bu da keçər.", "Hər çətin şeyin arxasında yaxşılıq gözləyir! 🌈"]},
    {"triggers": ["əgər", "eger", "bəlkə", "belke", "sanki"],
     "replies": ["Maraqlı düşüncə! 😊 Davam et, dinlirəm.", "Bəlkə həqiqətən! 🤔 Nə düşünürsən?"]},
    {"triggers": ["yenə", "yene", "təkrar", "tekrar", "yenidən", "yeniden"],
     "replies": ["Yenidən xoş gördük! 😊 Nə lazımdır?", "Hər zaman buradayam! 🤖 Nə soruşmaq istəyirsən?"]},
    {"triggers": ["çox", "cox", "az", "biraz"],
     "replies": ["Nə haqqında danışırsınız? Daha ətraflı izah edin.", "Ətraflı söyləyin, dinlirəm."]},

    # ─── Sleep & rest ──────────────────────────────────────────────────────────
    {"triggers": ["yata bilmirəm", "yata bilmirem", "yuxum gəlmir", "yuxum gelmir",
                  "gecə yata bilmirəm", "yuxusuzluq"],
     "replies": ["Yuxusuzluq çox yorucu olur. Telefonu yatmazdan əvvəl bir az kenara qoy, isti çay iç. Oda havasını dəyiş.",
                 "Gecə yatmaq üçün: ekrandan uzaqlaş, oda qaranlıq olsun, dərin nəfəs al. Bir müddətdə keçər.",
                 "Yuxusuzluqda isti süd kömək edir. Uzun sürərsə həkimə soruş."]},
    {"triggers": ["çox yuxuluyam", "cox yuxuluyam", "yuxum var", "yatmaq istəyirəm",
                  "yatmak isteyirem", "gözlərim yumular"],
     "replies": ["Yaxşı bir yuxu al, özünü yenilə. Qayıdanda söhbət edərik.",
                 "Yat, istirahət et. Yuxu hər şeyin dərmanıdır.",
                 "Xoş yuxular! Dinc yat, sağlıqla qalx."]},
    {"triggers": ["erkən qalxdım", "erken qalxdim", "sübh tezdən", "sabah erkən",
                  "sübhün birindən"],
     "replies": ["Erkən qalxmaq böyük alışqanlıqdır! Günü səmərəli istifadə et.",
                 "Sübh tezdən qalxanlar dünyanın yarısını fəth edir deyiblər. Uğurlu gün olsun!"]},
    {"triggers": ["pis yuxu gördüm", "yuxu gördüm", "kabuslar", "kabus gördüm"],
     "replies": ["Pis yuxular yalnız yuxudur — həqiqi deyil. Bir stəkan su iç, rahatlat özünü.",
                 "Kabus görmək çox narahat edicidir. Amma yuxu keçər, gerçək gözəldir."]},
    {"triggers": ["günorta yatıram", "qunduz yatıram", "şirin yuxuya getmişdim"],
     "replies": ["Günorta yuxusu 20 dəqiqə olsa ən faydalısıdır. Daha artıq olsa gecəki yuxuya zərər verə bilər.",
                 "Qısa yuxu verimlilik üçün əladır — klassik power nap!"]},

    # ─── Specific health symptoms ──────────────────────────────────────────────
    {"triggers": ["belim ağrıyır", "belim agriiyir", "bel ağrısı", "bel agrisi",
                  "omurgam ağrıyır", "arxa ağrım var"],
     "replies": ["Keçmiş olsun. Bel ağrısı üçün düz dur, uzun müddət oturma. Istilik kömək edir. Uzun sürərsə ortoped həkiminə bax.",
                 "Başın sağ olsun. Bel ağrısında isti duz kisəsi qoy. Ağır yük daşıma."]},
    {"triggers": ["dişim ağrıyır", "disim agriiyir", "diş ağrısı", "dis agrisi"],
     "replies": ["Keçmiş olsun! Diş ağrısı çox şiddətli olur. İlk imkanda stomatoloqa get, gecikdirmə.",
                 "Başın sağ olsun. Ağrıkəsici geçici kömək edir, amma əsl həll — diş həkiminə getməkdir."]},
    {"triggers": ["allergiyam var", "allerji var", "allerqiya", "qıcışır", "gözlərim sulanır"],
     "replies": ["Allergiyanı anlamaq üçün nəyə reaksiya verdiyini bil. Allerqoloqa müraciət etmək ən düzgün yoldur.",
                 "Allerji olan vaxtlarda pəncərəni bağlı saxla, çay iç. Antihistamin dərmanlar da kömək edir — amma həkimə soruş."]},
    {"triggers": ["ürəyim döyünür", "urekim doyunur", "ürək döyüntüsü", "nəfəsim darıxır"],
     "replies": ["Əgər çox güclü və qəfildən baş verirsə, dərhal həkimə zəng et. Sakit qal, dərin nəfəs al.",
                 "Ürək döyüntüsü stressdən, koffeindən ya fiziki yorğunluqdan ola bilər. Sakit ol, istirahət et. Davam edərsə həkimə müraciət et."]},
    {"triggers": ["burunum axır", "burnumdan qan", "burun tıxanıb", "burnun gedir"],
     "replies": ["Burun axması əksər vaxt zökəm əlamətidir. İsti su buxarı çək, bol su iç.",
                 "Keçmiş olsun. İsti içki iç, istirahət et. Çox davam edərsə həkimə bax."]},
    {"triggers": ["əzginlik", "üzgünəm", "taqətsizəm", "gücsüzəm", "zəiləm"],
     "replies": ["Bəzən bədən 'istirahət lazımdır' deməyin yeganə yolu budur. Bir az yat, yaxşı ye.",
                 "Əzginlik dəmir çatışmazlığından ya yuxusuzluqdan ola bilər. Qidalanmana diqqət et. Uzun sürərsə analiz ver."]},

    # ─── Mental & emotional health ─────────────────────────────────────────────
    {"triggers": ["depressiyam", "depressiyaya düşmüşəm", "depression", "çox pis vəziyyətdəyəm"],
     "replies": ["Bu hissiyat çox ağırdır, bunu bilirəm. Amma tək deyilsən — bir psixoloqa müraciət etmək çox kömək edə bilər. Bu cəsarət işidir.",
                 "Depressiya real bir halətdir, zəiflik yox. Yaxın birinə aç, ya mütəxəssisə müraciət et. Yalnız deyilsən."]},
    {"triggers": ["həyatdan bezmişəm", "hayatdan bezmisem", "yoruldum həyatdan",
                  "artıq dözə bilmirəm", "artiq doze bilmirem"],
     "replies": ["Bu hissiyatı başa düşürəm. Çox ağır anlarda belə bir sabahın fərqli olacağını unutma. Bir yaxınınla danış, ya mütəxəssisə müraciət et.",
                 "Bu anlarda ən vacib şey yalnız qalmamaq. Bir dostuna zəng et, söhbət et."]},
    {"triggers": ["özümü lazımsız hiss edirəm", "lazımsızam", "mənə ehtiyac yoxdur",
                  "heç kim umursamır"],
     "replies": ["Sən lazımsan — bunu bilmək istəyirəm. Bəzən ətraf bunu düzgün ifadə edə bilmir. Bir yaxın insanla dan.",
                 "Bu hissi anlamaq olar, amma bu duyğu həqiqəti əks etdirmir. Sən dəyərli bir insansan."]},
    {"triggers": ["özümü bağışlaya bilmirəm", "peşmanam", "etdiyimə görə üzülürəm",
                  "günahkaram", "xəta etdim"],
     "replies": ["Hər insan xəta edir. Əsl güc bunu qəbul edib irəliləməkdir. Özünü bağışlamaq öyrənilən bir şeydir.",
                 "Peşmanlıq dəyişmək istədiyini göstərir — bu artı bir keyfiyyətdir. Özünü cəzalandırma, düzəlt və davam et."]},
    {"triggers": ["kimsə məni başa düşmür", "basa dusmurler", "yaxınlarım anlamır",
                  "tək qalmışam", "dəstək yoxdur"],
     "replies": ["Bu həm kədərli, həm yorucudur. Özünü ifadə etmək çətin ola bilər. Yazıb-çizmək ya bir mütəxəssisə danışmaq kömək edir.",
                 "Bəzən ən yaxın insanlar belə anlaya bilmir — bu sənin problemin deyil. Hissiyyatlarını yazmaq rahatladıcıdır."]},
    {"triggers": ["narahatam", "narahat edirəm", "həyəcanlıyam", "həyəcanım var",
                  "endişə edirəm", "endise edirem"],
     "replies": ["Narahatlıq çox tanış hisdir. Dərin nəfəs al, ən pis senarionu düşün — çox vaxt problem o qədər böyük deyil.",
                 "Narahatlıq zamanı: nəfəs al, hissiyyatı qəbul et, amma onun sənə yol göstərməsinə icazə vermə."]},
    {"triggers": ["stress çox", "çox stresəm", "cox stresem", "stress altındayam"],
     "replies": ["Stres zamanı ilk addım: dərin nəfəs al, sakinləş. Sonra vəziyyətə addım-addım bax.",
                 "Stres çox vaxt hər şeyi eyni anda həll etmək istəməkdən gəlir. Bir şeyə fokuslan, qalanını sabaha burax."]},

    # ─── Food & cooking specifics ──────────────────────────────────────────────
    {"triggers": ["plov", "az plov", "azərbaycan plovu"],
     "replies": ["Plov Azərbaycan mətbəxinin tacıdır! Kəsməli, şüyüdlü, toyuqlu — hər növü ayrı-ayrı lezizdir.",
                 "Azərbaycan plovunu tam bişirmək sənətdir. Dəmə getmiş düyü, sarıyağ... iştahım açıldı!"]},
    {"triggers": ["dolma", "yarpaqdolma", "kələm dolması"],
     "replies": ["Dolma Azərbaycanlının ürəyindən keçər. Yarpaq, kələm, pomidor dolması — hamısı ayrı bir zövqdür!",
                 "Dolma bişirmək sevgi işidir. Yarpaqları düzdürmək, ət qarışdırmaq — hər addımı xüsusidir."]},
    {"triggers": ["kutab", "kutab bişirmək", "kutab yerim"],
     "replies": ["Kutab Azərbaycana xas bir xörəkdir — qabaqlı, göyərtilikli, ətli. Xalı kimi düzülür, şabaşlı yeyilir!",
                 "Kutabı ən gözəl qaynar-qaynar yemək lazımdır. İştah olsun!"]},
    {"triggers": ["səhər yeməyi", "seher yemeyi", "breakfast", "sabah nə yeyim"],
     "replies": ["Səhər yeməyi günün ən vacib öyünüdür. Yumurta, pendir, çay — Azərbaycan səhəri əladır!",
                 "Yaxşı bir səhər yeməyi: yumurta ya yulaf, meyvə, bol su. Günə enerji ilə başlayarsan."]},
    {"triggers": ["fast food", "hamburger", "pizza", "fastfood"],
     "replies": ["Fast food ara sıra yaxşıdır, amma hər gün olmaz. Ev yemeyi həmişə daha sağlıqlıdır.",
                 "Hamburger, pizza — bəzən bu da lazım olur! Amma ev yeməyi ilə növbəli saxla."]},
    {"triggers": ["sushi", "suşi", "yapon yeməyi"],
     "replies": ["Sushi çox populyarlaşıb! Gözəl dadı var.",
                 "Yapon mətbəxi çox maraqlıdır. Sushi yalın, faydalı, dadlıdır."]},
    {"triggers": ["ac deyiləm", "ac deyilim", "iştahım yoxdur", "istahim yoxdur",
                  "yemək istəmirəm"],
     "replies": ["İştahsızlıq stressdən ya yuxusuzluqdan ola bilər. Az-az ye, amma at.",
                 "Yemək istəmyəndə zorlamaq lazım deyil. Yüngül bir şey iç — bir az sonra iştah açılar."]},
    {"triggers": ["nə bişirim", "ne bismirem", "nə hazırlayım", "resept ver",
                  "yemek resepti"],
     "replies": ["Asan və dadlı: makaron, pomidor sousu, pendir. 20 dəqiqəyə hazır!",
                 "Tez hazır yemək: yumurta qızartması, pendir, çay. Qazan azalda-azalda hazır olar.",
                 "Tez istəsən, yuxa bürməsi çox sadədir. Düyü pilavı da tez olur."]},
    {"triggers": ["şirniyyat yemək", "desert", "tort yerim", "şokolad yeyim"],
     "replies": ["Şirniyyat bəzən lazım olur — stres açar! Amma artıq olmaz.",
                 "Azərbaycan şirniyyatları — şəkərbura, paxlava, nanbəy — hər birisi ayrı bir zövqdür."]},
    {"triggers": ["vegetarian", "ət yemirəm", "et yemirem", "vegan"],
     "replies": ["Vegetarian qidalanma sağlamlıq üçün çox faydalıdır. Azərbaycan mətbəxindən: borani, güveç, göyərti xörəkləri — hamısı ətsizdər.",
                 "Vegan da, vegetarian da — qidalanma seçimi şəxsi işdir. Sağlıqlı qal!"]},

    # ─── Technology & daily digital life ──────────────────────────────────────
    {"triggers": ["telefonum sıradan çıxdı", "telefonum işləmir", "telefon dondu",
                  "telefon xarab oldu"],
     "replies": ["Yenidən başlat — əksər problemlər beləcə həll olur. Olmadısa, servisə apar.",
                 "Telefon problemi sinir pozucu olur. Yenidən başlatmağı cəhd et, yaddaşı yoxla."]},
    {"triggers": ["pil bitdi", "batareyam bitdi", "şarjım yoxdur", "sarj yoxdur"],
     "replies": ["Şarj axtarışı — müasir insanın ən böyük problemi! Əl altında power bank saxlamaq yaxşı adətdir.",
                 "Şarj bitib — ağrılı hisdir. Powerbank al, bir daha yaşamarasın bu anı."]},
    {"triggers": ["internet yoxdur", "wifi işləmir", "internet kəsildi", "bağlantı yoxdur"],
     "replies": ["Routeri söndür, 30 saniyə gözlə, yenidən aç. Əksər vaxt kömək edir!",
                 "İnternetsizlik müasir əzabdır. Router restart, operator xəttinə zəng — addım-addım gedək."]},
    {"triggers": ["şifrəmi unutdum", "sifre unutdum", "parol yaddan çıxdı"],
     "replies": ["'Şifrəni unutdum' bölümünü istifadə et — əksər saytlarda var. Email ya telefon vasitəsilə sıfırlana bilər.",
                 "Şifrə meneceri istifadə etməyi məsləhət görürəm — bir daha yaşamazsın bunu."]},
    {"triggers": ["instagram", "insta"],
     "replies": ["Instagram gündə neçə dəqiqə istifadə edirsən? Sağlam istifadə vacibdir — scroll etmək stres artıra bilər.",
                 "Instagram vizual dünya — gözəl məzmun var, amma real həyatı da unut."]},
    {"triggers": ["youtube", "video baxıram"],
     "replies": ["YouTube bilik xəzinəsidir — öyrənmək üçün böyük platforma. Nə izləyirsən?",
                 "YouTube-da vaxt uçur! Bir başladın mı, qurtarmaq çətindir."]},
    {"triggers": ["tiktok"],
     "replies": ["TikTok çox addiktiv ola bilər! Özünə limit qoy ki, saatlarla keçib getməsin.",
                 "TikTok-da maraqlı məzmun çox var, amma vaxt yeyən bir platformadır."]},
    {"triggers": ["onlayn alış-veriş", "online alisveris", "internetten alıram", "çatdırılma"],
     "replies": ["Onlayn alış-veriş çox rahatdır, amma mağazaya getməkdə ayrı bir zövq var!",
                 "Çatdırılmanı gözləmək — xüsusi bir həyəcandır. Nə sifariş etdin?"]},
    {"triggers": ["video zəng", "video danışmaq", "zoom", "meet", "videocall"],
     "replies": ["Video zəng uzaqda olan insanlarla qoşalmağın ən yaxşı yoludur!",
                 "Zoom yorğunluğu real şeydir — hər şeyi video zənglə həll etməyə çalışmaq yorur."]},
    {"triggers": ["oyun oynayıram", "oyun oynayiram", "video game", "steam", "playstation"],
     "replies": ["Oyunlar əyləncəlidir! Amma fasilə verməyi unutma — göz və bel üçün vacibdir.",
                 "Hansı oyun oynayırsan? Macəra, strateji, yarış — hər növ ayrı dünya!"]},

    # ─── Work & career ─────────────────────────────────────────────────────────
    {"triggers": ["iş müsahibəsi", "is musibehi", "müsahibəyə gedirəm", "interview"],
     "replies": ["Müsahibədə əsas: şirkəti öyrən, cavablarını əvvəlcədən düşün, özünə güvən. Uğurlar!",
                 "Müsahibədə sakit qal. Sualları diqqətlə dinlə, tələsik cavab vermə. Hər şey yaxşı keçəcək!"]},
    {"triggers": ["işdən çıxmaq istəyirəm", "isten cixmaq isteyirem", "istefa"],
     "replies": ["Yeni başlanğıc üçün cəsarət lazımdır. Amma tərk etməzdən əvvəl növbəti addımı planlaşdır.",
                 "İstefa ciddi addımdır. Bir planın varsa — davam et. Yoxdursa — əvvəlcə planla, sonra addım at."]},
    {"triggers": ["terfi", "tərfi aldım", "vəzifəm artdı", "maaşım artdı"],
     "replies": ["Təbrik edirəm! Bu əzmkarlığının mükafatıdır. Layiqdisən!",
                 "Əla xəbər! Uğurların getdikcə artacaq."]},
    {"triggers": ["iş yükü çoxdur", "is yuku coxdur", "deadline var", "tarix sıxışır"],
     "replies": ["İş yükü çox olduqda: öncelikli işlərə bax, siyahı yaz, addım-addım get. Hər şeyi birdən etməyə çalışma.",
                 "Deadline stresinde: ən vacibini müəyyənləşdir. Fasilə ver, sonra davam et."]},
    {"triggers": ["uzaqdan işləyirəm", "uzaqdan isleyirem", "evdən işləyirəm", "remote work"],
     "replies": ["Evdən iş azadlıq verir, amma disiplin tələb edir! Sabit iş yeri, iş saatları — düzəni qur.",
                 "Remote work mükəmməldir — trafik olmadan! İşlə ev həyatını ayır ki, burnout olmayasan."]},
    {"triggers": ["iş yoldaşım ilə problem", "is yoldasi", "kolleqa ilə problem",
                  "müdirim", "bossum"],
     "replies": ["İş yerindəki anlaşmazlıq çox narahat edici olur. Sakin bir mühitdə bilavasitə danışmağı cəhd et.",
                 "İş yerindəki konfliktdə: hissiyyatla deyil, faktlarla danış. Ortaq həll axtarın."]},
    {"triggers": ["burnout", "yanmışam", "tükənmişəm", "işdən bezib"],
     "replies": ["Burnout real və ciddi bir haldır. Bir az vaxt götür, nəfəs al. Özünə baxmaq vəzifəndir.",
                 "Burnoutda ən vacib şey — dayanmaq. İzin al, heç bir şey düşünmə. Bədən siqnal verir, onu dinlə."]},
    {"triggers": ["karyera dəyişikliyi", "sahəmi dəyişmək", "yeni iş axtarıram"],
     "replies": ["Karyera dəyişikliyi cəsarət işidir. Güclü tərəflərini bil, yeni sahəni araşdır, CV-ni yenilə.",
                 "Yeni başlanğıclar həmişə mümkündür. Hər yaşda, hər mərhələdə. İlk addım ən çətin olanıdır."]},

    # ─── Relationships & social ────────────────────────────────────────────────
    {"triggers": ["yeni dost tapdım", "yeni tanışlıq", "yeni dost", "dost olduq"],
     "replies": ["Yeni dostluq həmişə xoşdur! Açıq ol, dinləyici ol — yaxşı dostluqlar zamanla qurulur.",
                 "Yeni tanışlıq — həyatın gözəl sürprizlərindən biri."]},
    {"triggers": ["dostumu itirdim", "dostluq qurtardı", "dostum küsdü"],
     "replies": ["Dostluğu itirmək ağrılıdır. Əgər dəyərli idisə, açıq bir söhbət etməyi cəhd et.",
                 "Dostluqlar bəzən gedir. Bu ağrı keçər. Əsl dostlar sonunda qalır."]},
    {"triggers": ["ayrılmışam", "ayrildim", "ilişkim qurtardı", "break up"],
     "replies": ["Ayrılıq çox ağır gəlir. Vaxt keçir, yara iyileşir. Özünə qulluq et, yaxınların yanında ol.",
                 "Keçmiş olsun. Bəzən ayrılıqlar yeni bir başlanğıcdır. Özünü tanı, güclən, irəliləy."]},
    {"triggers": ["münasibət problemim var", "munasibetde problem", "sevgilim ilə dalaşdım"],
     "replies": ["Hər münasibətdə anlaşmazlıqlar olur. Hissiyyatlarınızı sakit bir mühitdə danışın.",
                 "İlişkidəki çətinliklər söhbətlə həll olur — amma hər ikisi danışmağa hazır olmalıdır."]},
    {"triggers": ["sevdiyimi söyləyə bilmirəm", "etiraf edə bilmirəm", "çəkinirəm söyləməkdən"],
     "replies": ["Hissiyyatını söyləmək cəsarət istəyir. Amma deyilməyən hissiyyat içdə qalır — bu daha ağır olur.",
                 "Bir gün söyləməsən, bir gün peşman ola bilərsən. Vaxtında demək lazımdır."]},
    {"triggers": ["qısqanclıq", "qisqaniqliq", "qısqanıram", "qisqaniram"],
     "replies": ["Qısqanclıq hissiyyatı normaldır, amma hərəkətə çevrilərsə problemdir. Güvən üzərında işlə.",
                 "Qısqanclığın kökü bəzən güvənsizlikdir. Özünə inan, partnyorunla danış."]},
    {"triggers": ["uzaqdan münasibət", "uzaqdan sevgi", "long distance", "fərqli şəhərdə"],
     "replies": ["Uzaqdan münasibət çətindir, amma mümkündür. Ünsiyyət, etibar, ortaq planlar — əsaslardır.",
                 "Uzaqlıq sınar, amma güclü münasibəti qıra bilmir. Sadiq qalın, ünsiyyəti kəsməyin."]},
    {"triggers": ["evlilik", "evlenmek", "evlənirəm", "nişanlıyam", "nişanam"],
     "replies": ["Maşallah! Xoşbəxt günlər olsun. Evlilik böyük addımdır — hazırlıqlı ol, həvəslə gir!",
                 "Nişan mübarək! Ömürlük bir dostluğun başlanğıcıdır. Uğurlar!"]},

    # ─── Sports & fitness ─────────────────────────────────────────────────────
    {"triggers": ["qaçıram", "qaçmağa başladım", "running", "jogging"],
     "replies": ["Qaçmaq ən əlçatan idman növüdür! Hava-havaya çıx, ruh yüksəlir, bədən güclənir.",
                 "Qaçış rutini qurmaq əladır. Yavaş başla, tədricən artır. Ayaqqabını düzgün seç."]},
    {"triggers": ["fitnes", "fitness", "gym", "zalda idman", "bədən qurmaq"],
     "replies": ["Zal idmanı mükəmməldir! Disiplin + düzgün qidalanma = nəticə.",
                 "Zalda idman üçün: əvvəlcə həkim məsləhəti, sonra proqram qur, sonra bağlan."]},
    {"triggers": ["üzürəm", "hovuzda", "yüzmək", "swimming"],
     "replies": ["Üzmək bütün əzələlərə eyni anda çalışdıran ən tam idmandır! Əladır.",
                 "Üzmək bədən üçün möhtəşəm idmandır — həm oynaq, həm effektiv."]},
    {"triggers": ["futbol baxmışam", "match baxdım", "məç baxdım", "qol vurdular"],
     "replies": ["Futbol tamaşası ayrı bir həyacandır! Nəticə necə oldu?",
                 "Futbol mövsümü — həyəcanın qurtarmadığı vaxt! Nə baxdın?"]},
    {"triggers": ["qol vurdum", "qazan", "idmanda uğur", "yarışda qazandım"],
     "replies": ["Təbrik edirəm! Zəhmət meyvəsini verdi. Belə davam et!",
                 "Əla! Bu cür uğurlar motivasiyanı artırır. Növbəti hədəf nədir?"]},

    # ─── Music & entertainment ─────────────────────────────────────────────────
    {"triggers": ["mahnı tövsiyə et", "mahni tavsiye et", "yaxşı mahnı", "nə dinləyim"],
     "replies": ["Azərbaycan musiqisindən: Şövkət Ələkbərova, Rəşid Behbudov — klassiklər. Müasirdən Miri Yusif, Natavan Həsənova.",
                 "Əhvalına görə dəyişir. Kədərli üçün yavaş melodiyalar, şən üçün ritmik. Hansı əhvaldasan?"]},
    {"triggers": ["muğam", "mugam", "aşıq havası", "xalq musiqisi"],
     "replies": ["Muğam Azərbaycanın musiqi xəzinəsidir — UNESCO qoruması altındadır. Şüştər, Segah, Çahargah...",
                 "Aşıq havası ruhun dilidir. Qopuz, saz, yarım qalan kəlmə — sözün gücü!"]},
    {"triggers": ["konsert", "konser", "canlı musiqi"],
     "replies": ["Canlı konsert ayrı bir hissdir — studiya ilə müqayisə olmaz. Hansı konsertə gedirdin?",
                 "Konsertin heyəcanı biracə dünya. Hansı ifaçı idi?"]},
    {"triggers": ["film tövsiyə et", "nə baxım", "yaxşı film", "film önerisi"],
     "replies": ["Janrın nədir? Dram, komediya, triller, fantastika — hamısından ən yaxşılar var.",
                 "Nə seversin — macəra, duyğusal, gülməli? Ona görə tövsiyə verərəm."]},
    {"triggers": ["serial", "dizi", "netflix", "binge watching"],
     "replies": ["Serial binge çox cazip gəlir! Amma yatmağı unutma, sabah da var.",
                 "Hansı serial izləyirsən? Türk, koreya, Avropa — hər biri ayrı dünya."]},
    {"triggers": ["podcast", "podkast dinliyirəm"],
     "replies": ["Podcast böyük öyrənmə vasitəsidir — yol boyu, idman zamanı, evdə. Hansı mövzu?",
                 "Podcast dinləmək çox inkişaf etdirici adətdir. Azərbaycanca podkastlar da var artıq."]},

    # ─── Pets & animals ───────────────────────────────────────────────────────
    {"triggers": ["itim var", "köpəyim var", "itim", "kopeyim"],
     "replies": ["Köpək ən sadiq dostdur! Gündəlik gəzinti, oynamaq — onların ehtiyacları sadədir.",
                 "Köpəkli ev daha şən olur! Adı nədir?"]},
    {"triggers": ["pişiyim var", "pişik bəsləyirəm", "pisik", "mushugum"],
     "replies": ["Pişiklər öz dünyalarında yaşayır — bunu sevmək lazımdır! Adı nədir?",
                 "Pişik bəsləmək çox sakinləşdiricidir. Mirnası da, könlünü alan da."]},
    {"triggers": ["quşum var", "tutuquşu", "kanarya", "quş bəsləyirəm"],
     "replies": ["Quş bəsləmək çox maraqlıdır! Oxuyanlar evə həyat gətirir.",
                 "Tutuquşular nitq öyrənir — möhtəşəm məxluqlardır!"]},
    {"triggers": ["heyvanımı itirdim", "heyvanim oldu", "it-pişik öldü"],
     "replies": ["Heyvan itkisi çox ağır olur — onlar da ailə üzvüdür. Hüznünə şərik oluram.",
                 "Başın sağ olsun. Ev heyvanının itkisi real bir kədir olur. Özünə qulluq et."]},

    # ─── Shopping & lifestyle ──────────────────────────────────────────────────
    {"triggers": ["alış-veriş etdim", "alisveris etdim", "mağazaya getdim", "bazara getdim"],
     "replies": ["Alış-veriş gəzintisi həm əyləncəlidir, həm yorucu! Nə aldın?",
                 "Bazardan qayıdanda pul gedir, amma ürək dolar!"]},
    {"triggers": ["endirim", "sale", "kampaniya", "ucuz tapdım"],
     "replies": ["Endirim zamanı alış-veriş — ayrı bir həyəcandır! Yaxşı tapdın?",
                 "Yaxşı qiymət tutmaq da bir sənətdir! Təbrik edirəm."]},
    {"triggers": ["hədiyyə almaq", "hediyye almaq", "doğum günü hədiyyəsi",
                  "hədiyyə seçirəm"],
     "replies": ["Hədiyyə seçimi çətin olur! Ən yaxşısı insanın marağını bil, ona uyğun seç.",
                 "Hədiyyədə qiymət deyil, düşüncə vacibdir. Bir kitab, bir şirniyyat — gözəl ola bilər."]},
    {"triggers": ["geyim almaq", "paltar", "moda", "fashion"],
     "replies": ["Moda şəxsiyyəti ifadə edir. Sənə yaraşanı seç, başqasını deyil.",
                 "Ən yaxşı geyim özündə rahat hissettirəndir. Rahat + stil = mükəmməl."]},

    # ─── Holidays & celebrations ───────────────────────────────────────────────
    {"triggers": ["tətil planım var", "yay planı", "tatilə gedirəm", "istirahətə çıxıram"],
     "replies": ["Tətil — ən gözlənilən andır! Hara gedirsin?",
                 "Yaxşı istirahət etmək hüququndur. Nə planlaşdırmısan?"]},
    {"triggers": ["novruz gəlir", "novruz hazırlığı", "novruz bayramı"],
     "replies": ["Novruz — baharın, yenilenmenin bayramıdır! Xonça, semeni, tonqal — hər birisi simvoldur.",
                 "Novruz bayramınız mübarək olsun! Siz bu bayramı necə keçirirsiniz?"]},
    {"triggers": ["il başı gecəsi", "yeni il gecəsi", "yeni il hazırlığı"],
     "replies": ["Yeni il gecəsi — hər şeyi yenidən başlatmaq fürsəti! Nə planlaşdırmısan?",
                 "İl başı gecəsi əhvalı yüksəkdir. Arzularını yaz — sonra bax neçəsi çıxdı!"]},
    {"triggers": ["doğum günüm var", "doğum günüm gəlir", "yaş dolur"],
     "replies": ["Doğum günün mübarək olsun — özündən əvvəl! Nə hiss edirsən bu il?",
                 "Ad günün mübarək! Hər ili daha güclü, daha bilikli, daha xoşbəxt keçir!"]},
    {"triggers": ["toyu var", "toy dəvəti aldım", "toya gedirik", "nişanı var"],
     "replies": ["Toylar Azərbaycanda böyük hadisədir! Xoş vaxt keçir, ürəkdən sevin!",
                 "Toy sevinci bölüşüldükcə artar. Xoşbəxt ol, həzz al!"]},

    # ─── Daily life humor & situations ────────────────────────────────────────
    {"triggers": ["tıxac var", "trafik", "traffik", "yolda qaldım", "sıxışdım yolda"],
     "replies": ["Tıxac — şəhər həyatının məşhur problemi! Podcast ya musiqi açmaq bu vaxtı daha yaxşı keçirir.",
                 "Tıxacda sakin qal, nəfəs al. Əvvəlcədən xəbər ver ki, gec qalacaqsansa."]},
    {"triggers": ["işə gecikdim", "işə geç qaldım", "gec qaldım", "yubandım"],
     "replies": ["Gecikdikdə: gözləyənə xəbər ver, bəhanə uydurma — dürüst ol.",
                 "İşə gecikdikdə sakin qal, əvvəlcə xəbər ver, sonra tez get."]},
    {"triggers": ["açarımı itirdim", "açar yox", "əşyamı itirdim", "cüzdanım yoxdur"],
     "replies": ["Son gördüyün yeri xatırla. Sakit düşün — çox vaxt gördüyün yerdədir.",
                 "İtmiş əşyaları axtaranda: sonuncu istifadə etdiyin yeri düşün. Cib-çanta yoxla."]},
    {"triggers": ["bərk gün keçirdim", "pis gün idi", "gün çox ağır keçdi"],
     "replies": ["Bəzən günlər belə olur. Amma hər gün yeni bir gün. Sabah başqa cür olacaq.",
                 "Ağır gündən sonra özünə bir şey et — çay, kitab, yüngül gəzinti. Özünlə qalxmaq lazımdır."]},
    {"triggers": ["çox yaxşı gün keçirdim", "gözəl gün idi", "əla gün keçdi"],
     "replies": ["Nə gözəldir! Belə günlər ruhda iz buraxır. Nə oldu?",
                 "Yaxşı günlər xatırlansın! Nə etdin?"]},
    {"triggers": ["bazar ertəsi", "monday", "həftəyə başladım"],
     "replies": ["Bazar ertəsi yeni bir həftənin başlanğıcıdır! Bu həftənin 1 hədəfini müəyyənləşdir.",
                 "Bazar ertəsi: yeni şans, yeni həftə. Başla!"]},
    {"triggers": ["cümə axşamı", "cümə gəlir", "həftəsonu yaxınlaşır"],
     "replies": ["Cümə axşamı — həftəsonunun xəbərçisi! Planların var?",
                 "Cümə! Az qaldı istirahətin. Nə planlaşdırmısan?"]},
    {"triggers": ["həftəsonu bitdi", "pazar günü", "bazar günü"],
     "replies": ["Həftəsonu tez bitir — hamıya belə gəlir. Nə etdin ən azından?",
                 "Yeni həftə başlayır. Nə hazırlayırsan?"]},
    {"triggers": ["vaxtsızam", "vaxtim yoxdur", "vaxta yetişmirəm"],
     "replies": ["Vaxt problemi — çox tanış. Öncelik siyahısı yaz: ən vacib üç iş. Qalanları gözləyə bilər.",
                 "Vaxt hamıya 24 saatdır — fərq idarəetmədir. Nə ən çox vaxt aparır həyatında?"]},
    {"triggers": ["yalnız evdəyəm", "evdə tənhayam", "evdəyəm bir özüm"],
     "replies": ["Tənhalıqdan bəzən həzz almaq olar — özünlə baş-başa qalmaq da lazımdır.",
                 "Evdə tək qalmaq öz-özünü tanımaq fürsətidir. Sevdiyin bir şey et."]},
    {"triggers": ["motivasiyam yoxdur", "motivasiya yoxdur", "heç bir şey etmək istəmirəm"],
     "replies": ["Motivasiya gözləmə — başla. Başlamaq motivasiyanı özüylə gətirir.",
                 "Motivasiyasız gün olur. Ən kiçik şeydən başla: bir stəkan su, üç dərin nəfəs, sonra birinci addım."]},
    {"triggers": ["çox düşünürəm", "cox dusunurem", "overthinking", "fikirlərimdən çıxa bilmirəm"],
     "replies": ["Overthinking yorucu olur. Fikirləri kağıza yaz — başından çıxar. Daha yüngül olur.",
                 "Çox düşünmə tələsi: bir şeyi nə qədər düşünsək, o qədər böyüyür. Hərəkət et, düşüncəni kəs."]},

    # ─── Nature & outdoors ─────────────────────────────────────────────────────
    {"triggers": ["yürüyüşə çıxdım", "gəzintiyə getdim", "piyada gəzdim"],
     "replies": ["Gəzinti həm bədənə, həm ruha yaxşı gəlir. Nə gördün?",
                 "Piyada gəzmək ən sadə və faydalı fəaliyyətlərdən biridir. Davam et!"]},
    {"triggers": ["piknik", "piknikə getdik", "çölə çıxdıq"],
     "replies": ["Piknik — yaza xas ən gözəl gəzintidir! Hava yaxşı idi?",
                 "Təzə hava, açıq göy, dost-dost — piknik kimiymiş?"]},
    {"triggers": ["günbatımı gördüm", "gunbatiim gordum", "gözəl mənzərə"],
     "replies": ["Günbatımı — gün ötən hər gecənin ən gözəl xatirəsi. Foto çəkdin?",
                 "Belə anlar bizi 'yalnız bu an var' hissini yaşadır."]},
    {"triggers": ["yağış yağır", "yağiş yağiir", "hava yağışlıdır"],
     "replies": ["Yağış havası — çay, kitab, pəncərə mənzərəsi. Ən gözəl kombinasiya!",
                 "Yağış havası bəzilərini kədərləndirir, bəzilərini sakinləşdirir. Sənin üçün necədir?"]},
    {"triggers": ["qar yağır", "qar yağiır", "hava qarlıdır", "qar var"],
     "replies": ["Qar mənzərəsi möhtəşəmdir! Amma yollar sürüşkən olur — diqqətli ol.",
                 "Qarlı hava — çay iç, pəncərəyə bax, bir müddət sadəcə ol."]},
    {"triggers": ["yay istisi", "çox istidir", "hava boğucudur"],
     "replies": ["Yay istisindən: bol su iç, günün ən isti saatlarında kölgədə ol, yüngül gey.",
                 "Boğucu havada enerjiyi saxlamaq: soyuq su iç, ventilyator ya kondisioner istifadə et."]},
    {"triggers": ["payız gəldi", "xəzəl", "yarpaqlar saraldı"],
     "replies": ["Payız melanxoliyası özünəməxsus bir gözəlliyə malikdir. Sarı yarpaqlar, hava serinləyir...",
                 "Payız — düşüncəli, sakit, kitab mövsümü. Sevirsənmi payızı?"]},

    # ─── Self-improvement & learning ──────────────────────────────────────────
    {"triggers": ["kitab oxuyuram", "kitab bitirdim", "roman oxudum"],
     "replies": ["Oxumaq ən dəyərli adətlərdən biridir. Nə oxuyurdun?",
                 "Kitab bitirmək gözəl hissdir. Növbəti nədir?"]},
    {"triggers": ["yeni bacarıq öyrənirəm", "kurs keçirəm", "sertifikat alıram"],
     "replies": ["Özünü inkişaf etdirmək ən yaxşı investisiyadır. Hansı sahədir?",
                 "Hər yeni bacarıq sənə yeni bir qapı açır. Davam et!"]},
    {"triggers": ["meditasiya", "nəfəs məşqi", "yoga", "mindfulness"],
     "replies": ["Meditasiya ağlı sakinləşdirmək üçün güclü vasitədir. Hər gün 10 dəqiqə belə kömək edir.",
                 "Mindfulness — anı yaşamaq sənəti. Bu günümüzdə çox lazımlı bir vərdiş."]},
    {"triggers": ["gündəlik yazıram", "jurnal tuturam", "notes yazıram"],
     "replies": ["Gündəlik yazmaq öz-özünü tanımağın ən gözəl üsullarından biridir.",
                 "Düşüncələri kağıza dökmək ağırlaşan hissiyyatları yüngülləşdirir. Əla vərdiş!"]},
    {"triggers": ["hədəfim var", "hedef qoydum", "plan etdim"],
     "replies": ["Hədəf qoymaq birinci addımdır. İkincisi onu yazmaq, üçüncüsü hər gün kiçik addım atmaqdır.",
                 "Hədəflər olmasa, gün-güzəran olur. Hədəf olsa — hər gün istiqamət olur. Əladır!"]},
    {"triggers": ["ingilis dilini öyrənirəm", "ingilisçə oxuyuram", "dil kursunda"],
     "replies": ["İngilis dili bugünkü dünyada böyük üstünlükdür. Hər gün 15-20 dəqiqə yetər — davam et!",
                 "Dil öyrənmədə ən effektiv yol — hər gün istifadə etmək. Podcast, film, məqalə — hamısı kömək edir."]},
    {"triggers": ["rus dili", "türk dili", "fransız dili", "alman dili öyrənirəm"],
     "replies": ["Hər yeni dil yeni bir dünya açır. Sabit qal, hər gün az-az öyrən.",
                 "Dil öyrənmək zamanla olur. Tələsmə, vaxt ver — bacaracaqsan."]},

    # ─── General conversation expansion ───────────────────────────────────────
    {"triggers": ["maraqlı bir şey danış", "maraqli bir sey danis", "bir şey anlat",
                  "nə isə maraqlı de"],
     "replies": ["Bilirsənmi, bal arısı bir ömrüdə cəmi bir çay qaşığı bal istehsal edir. Buna rağmən biz tonlarla bal yeyirik.",
                 "Maraqlı fakt: insan həyatı boyu ortalama 70.000 fikir fikirləşir. Çoxunu heç yadda saxlaya bilmir.",
                 "Ən maraqlı şey bu anda baş verir — söhbətin özü! Nə haqqında danışmaq istəyirsən?"]},
    {"triggers": ["bilirsənmi", "bilirsenmi", "bilib bilib", "deyirdin"],
     "replies": ["Nə deməyə çalışırsan? Anlat, qulaq asıram.",
                 "Davam et, dinliyirəm. Nə bilirdin?"]},
    {"triggers": ["anlayırsanmı", "anlayirsinmi", "başa düşürsənmi"],
     "replies": ["Bəli, anlayıram! Davam et.",
                 "Başa düşürəm. Davam edin, dinlirəm."]},
    {"triggers": ["bir sualom var", "bir sualim var", "sual vermək istəyirəm",
                  "soruşmaq istəyirəm"],
     "replies": ["Buyur! Dinlirəm, soruş.",
                 "Soruş, cavab vermədə çalışarım."]},
    {"triggers": ["nə düşünürsən", "ne dusunursen", "fikirləşirsənmi"],
     "replies": ["Düşünürəm ki, cavab sualın içindədir. Sən nə düşünürsən?",
                 "Maraqlı sualsan. Öz fikrini de, sonra müzakirə edək."]},
    {"triggers": ["söylə", "danış", "anlat mənə", "de mənə"],
     "replies": ["Buyur, nə haqqında?",
                 "Dinlirəm, anlat."]},
    {"triggers": ["yaxşı", "tamam", "okay", "ok"],
     "replies": ["Əla! Başqa nə var?",
                 "Tamam! Nə lazımdır?"]},
    {"triggers": ["xoş gördük", "xos gorduk", "çoxdandır", "coxdandir",
                  "haradaydın", "hardaydin"],
     "replies": ["Çoxdandır! Nə gəzir?",
                 "Xoş gördük! Harda idin bu vaxt?",
                 "Burdayam həmişə! Sən harada idin?"]},
    {"triggers": ["maraq edirəm", "maraqli gordum", "maraq etdi", "merak etdim"],
     "replies": ["Hansı barədə?",
                 "Nəyi maraqlandı?"]},
    {"triggers": ["başqa nə var", "başqa nə bilirsin", "daha nə deyə bilərsən"],
     "replies": ["Daha nə bilmək istəyirsən? Zarafat, fakt, sitat — seç birini.",
                 "Zarafat eşitmək istəyirsən? Yaz: Zarafat et!"]},
    {"triggers": ["unuttum", "yadımdan çıxdı", "yaddan çıxdı"],
     "replies": ["Heç nə yada düşmürdü? Normal! Yazıb qoymaq unudmamağın ən etibarlı üsuludur.",
                 "Hər şeyi yadda saxlamaq mümkün deyil. Vacib şeyləri qeyd al, gerisi yüngülləşər."]},
    {"triggers": ["düz deyirsən", "haqlısan", "haqsız deyilsən"],
     "replies": ["Sağ ol! Amma sən də düz başlayırsan.",
                 "Birlikdə düşünmək həmişə daha yaxşı nəticə verir."]},
    {"triggers": ["razıyam", "raziyam", "razı gəlirəm", "qəbul edirəm"],
     "replies": ["Əla! Razılıq anlaşmağın başlanğıcıdır.",
                 "Razılıq — irəliləməyin açarıdır."]},
    {"triggers": ["razı deyiləm", "razı deyilem", "razılaşmıram"],
     "replies": ["Fikirlər fərqli ola bilər — bu normaldır. Niyə razılaşmırsansa anlat.",
                 "İtirazın haqlı ola bilər. Nə düşünürsən?"]},
    {"triggers": ["hansı daha yaxşıdır", "hansını seçim", "birini seç"],
     "replies": ["Vəziyyətdən asılıdır. Hər ikisinin üstünlüklərini yaz, sonra qərar ver.",
                 "Hər iki variant öz-özündə yaxşıdır. Sənin üçün nə vacibdir — ona görə seç."]},
    {"triggers": ["inanılmaz", "inandım", "inanmadım"],
     "replies": ["Bəzən həqiqət inanılmaz gəlir!",
                 "Həqiqəti dürüstcə söyləmək lazımdır, inansın ya inanmasın."]},
    {"triggers": ["gülünc", "gulunc", "çox gülməli", "cox gulmeii"],
     "replies": ["Gülmək ömür uzadır — bu həm zarafat, həm həqiqətdir!",
                 "Gülüş ən yaxşı dərmandır."]},
    {"triggers": ["işlər yaxşı gedir", "isler yaxsi gedir", "hər şey qaydasındadır"],
     "replies": ["Çox gözəldir! Bu halı qoru.",
                 "Yaxşı gedirsə — davam et. Axını pozma."]},
    {"triggers": ["yeniliklər var", "xəbər var", "nə xəbər", "yeni nə var"],
     "replies": ["Xəbəri paylaş! Qulaq asıram.",
                 "Yenilik var? Danış, dinliyirəm."]},
]
